var plist = [
    { tag:'adlm', name:'Adlam', url:'adlm/index.html' },
    { tag:'arab', name:'Arabic', url:'arab-ar/index.html' },
    { tag:'arab', name:'Hausa', url:'arab-ha/index.html' },
    { tag:'arab', name:'Kashmiri', url:'arab-ks/index.html' },
    { tag:'arab', name:'Persian', url:'arab-fa/index.html' },
    { tag:'arab', name:'Uighur', url:'arab-ug/index.html' },
    { tag:'arab', name:'Urdu', url:'arab-ur/index.html' },
    { tag:'arab', name:'Wolof', url:'arab-wo/index.html' },
    { tag:'arab', name:'Pan-African&nbsp;Arabic', url:'arab-afr/index.html' },
    { tag:'arab', name:'All&nbsp;Arabic', url:'arab-all/index.html' },
    { tag:'armi', name:'Aramaic', url:'armi/index.html' },
    { tag:'armn', name:'Armenian', url:'armn/index.html' },
    { tag:'bali', name:'Balinese', url:'bali/index.html' },
    { tag:'bamu', name:'Bamum', url:'bamu/index.html' },
    { tag:'bass', name:'Bassa Vah', url:'bass/index.html' },
    { tag:'batk', name:'Batak', url:'batk/index.html' },
    { tag:'beng', name:'Bengali', url:'beng/index.html' },
    { tag:'bugi', name:'Buginese', url:'bugi/index.html' },
    { tag:'buhd', name:'Buhid', url:'buhd/index.html' },
    { tag:'cans', name:'Eastern Canadian Inuktitut', url:'cans-ike/index.html' },
    { tag:'cans', name:'Plains Cree', url:'cans-crk/index.html' },
    { tag:'cans', name:'All&nbsp;UCAS', url:'cans/index.html' },
    { tag:'cher', name:'Cherokee', url:'cher/index.html' },
    { tag:'cyrl', name:'Mongolian', url:'cyrl-mn/index.html' },
    { tag:'cyrl', name:'Russian', url:'cyrl-ru/index.html' },
    { tag:'cyrl', name:'Ukrainian', url:'cyrl-uk/index.html' },
    { tag:'cyrl', name:'All Cyrillic', url:'cyrl-all/index.html' },
    { tag:'deva', name:'Hindi', url:'deva-hi/index.html' },
    { tag:'deva', name:'Kashmiri', url:'deva-ks/index.html' },
    { tag:'deva', name:'All Devanagari', url:'deva-all/index.html' },
    { tag:'egyp', name:'Egyptian&nbsp;hieroglyphs', url:'egyptian/index.html' },
    { tag:'elym', name:'Elymaic', url:'elym/index.html' },
    { tag:'ethi', name:'All Ethiopic', url:'ethi/index.html' },
    { tag:'ethi', name:'Amharic', url:'ethi-am/index.html' },
    { tag:'geor', name:'Modern Georgian', url:'geor-ka/index.html' },
    { tag:'geor', name:'Khutsuri', url:'geok-ka/index.html' },
    { tag:'geor', name:'All Georgian', url:'geor-all/index.html' },
    { tag:'glag', name:'Glagolitic', url:'glag/index.html' },
    { tag:'goth', name:'Gothic', url:'goth/index.html' },
    { tag:'grek', name:'Modern Greek', url:'grek/index.html' },
    { tag:'gujr', name:'Gujarati', url:'gujr/index.html' },
    { tag:'guru', name:'Gurmukhi', url:'guru/index.html' },
    { tag:'hano', name:'Hanunoo', url:'hano/index.html' },
    { tag:'hani', name:'Chinese', url:'hani/index.html' },
    { tag:'hatr', name:'Hatran', url:'hatr/index.html' },
    { tag:'hebr', name:'Hebrew', url:'hebr/index.html' },
    { tag:'jpan', name:'Japanese', url:'jpan/index.html' },
    { tag:'java', name:'Javanese', url:'java/index.html' },
    { tag:'kali', name:'Kayah Li', url:'kali/index.html' },
    { tag:'khmr', name:'Khmer', url:'khmr/index.html' },
    { tag:'laoo', name:'Lao', url:'lao/index.html' },
    { tag:'lana', name:'Northern&nbsp;Thai', url:'lana-nod/index.html' },
    { tag:'lana', name:'Tai&nbsp;Khün', url:'lana-kkh/index.html' },
    { tag:'latn', name:'Latin&nbsp;&amp;&nbsp;diacritics', url:'latn-all/index.html' },
    { tag:'latn', name:'Bamanan', url:'latn-bm/index.html' },
    { tag:'latn', name:'Fula', url:'latn-ff/index.html' },
    { tag:'latn', name:'Hausa', url:'latn-ha/index.html' },
    { tag:'latn', name:'IPA&nbsp;standard&nbsp;chart', url:'ipa/index.html' },
    { tag:'latn', name:'IPA&nbsp;by&nbsp;place', url:'ipa2/index.html' },
    { tag:'latn', name:'IPA&nbsp;by&nbsp;type', url:'ipa3/index.html' },
    { tag:'latn', name:'Old&nbsp;English', url:'latn-ang/index.html' },
    { tag:'latn', name:'Old&nbsp;Norse', url:'latn-non/index.html' },
    { tag:'latn', name:'Tłı̨chǫ&nbsp;(Dogrib)', url:'latn-dgr/index.html' },
    { tag:'latn', name:'Vietnamese', url:'latn-vi/index.html' },
    { tag:'latn', name:'Wolof', url:'latn-wo/index.html' },
    { tag:'lepc', name:'Lepcha', url:'lepc-lep/index.html' },
    { tag:'limb', name:'Limbu', url:'limb-lif/index.html' },
    { tag:'lisu', name:'Lisu (Fraser script)', url:'lisu/index.html' },
    { tag:'lyci', name:'Lycian', url:'lyci/index.html' },
    { tag:'lydi', name:'Lydian', url:'lydi/index.html' },
    { tag:'maka', name:'Makasar', url:'maka/index.html' },
    { tag:'mlym', name:'Malayalam', url:'mlym/index.html' },
    { tag:'mand', name:'Mandaic', url:'mand/index.html' },
    { tag:'mend', name:'Mende Kikakui', url:'mend/index.html' },
    { tag:'mong', name:'Mongolian', url:'mong-mn/index.html' },
    { tag:'mroo', name:'Mro', url:'mroo-mro/index.html' },
    { tag:'mymr', name:'Burmese', url:'mymr-my/index.html' },
    { tag:'mymr', name:'Shan', url:'mymr-shn/index.html' },
    { tag:'nagm', name:'Nag Mundari', url:'nagm-unr/index.html' },
    { tag:'nbat', name:'Nabataean', url:'nbat/index.html' },
    { tag:'newa', name:'Newa', url:'newa/index.html' },
    { tag:'nkoo', name:"N'Ko", url:'nko/index.html' },
    { tag:'olck', name:'Santali', url:'olck/index.html' },
    { tag:'orya', name:'Odia (Oriya)', url:'orya/index.html' },
    { tag:'osge', name:'Osage', url:'osge/index.html' },
    { tag:'palm', name:'Palmyrene', url:'palm/index.html' },
    { tag:'phli', name:'Pahlavi', url:'phli/index.html' },
    { tag:'plrd', name:'All&nbsp;Miao&nbsp;(Pollard)', url:'plrd/index.html' },
    { tag:'plrd', name:'A-Hmao', url:'plrd-hmd/index.html' },
    { tag:'prti', name:'Parthian', url:'prti/index.html' },
    { tag:'phnx', name:'Phoenician', url:'phnx/index.html' },
    { tag:'rjng', name:'Rejang', url:'rjng/index.html' },
    { tag:'rohg', name:'Hanifi Rohingya', url:'rohg/index.html' },
    { tag:'runr', name:'All Runic', url:'runr/index.html' },
    { tag:'runr', name:'Anglo-Saxon Runes', url:'runr-ang/index.html' },
    { tag:'talu', name:'New&nbsp;Tai&nbsp;Lue', url:'talu/index.html' },
    { tag:'sinh', name:'Sinhala', url:'sinh/index.html' },
    { tag:'sund', name:'Sundanese', url:'sund/index.html' },
    { tag:'sunu', name:'Sunuwar', url:'sunu-suz/index.html' },
    { tag:'syrc', name:'Assyrian&nbsp;Neo-Aramaic', url:'syrc-aii/index.html' },
    { tag:'syrc', name:'Christian Palestinian Aramaic', url:'syrc-axp/index.html' },
    { tag:'syrc', name:'Syriac', url:'syrc/index.html' },
    { tag:'syrc', name:'Turoyo', url:'syrc-tru/index.html' },
    { tag:'tagb', name:'Tagbanwa', url:'tagb/index.html' },
    { tag:'tale', name:'Tai&nbsp;Le', url:'tale/index.html' },
    { tag:'tavt', name:'Tai&nbsp;Viet', url:'tavt/index.html' },
    { tag:'taml', name:'Tamil', url:'taml/index.html' },
    { tag:'telu', name:'Telugu', url:'telu/index.html' },
    { tag:'tfng', name:'Neo-tifinagh', url:'tfng-zgh/index.html' },
    { tag:'tfng', name:'All Tifinagh ', url:'tfng-all/index.html' },
    { tag:'thaa', name:'Thaana', url:'thaa/index.html' },
    { tag:'thai', name:'Thai', url:'thai/index.html' },
    { tag:'tibt', name:'Tibetan', url:'tibt/index.html' },
    { tag:'ugar', name:'Ugaritic', url:'ugar/index.html' },
    { tag:'vaii', name:'Vai', url:'vai/index.html' },
    { tag:'yezi', name:'Yezidi', url:'yezi' },
]



var plistByRegion = {
	'A':[
			['<b>Adlam</b> ['],
				['Adlam/Pular','adlm/index.html'],
				[']'],
			['• <b>Arabic</b> ['],
				['MSA', 'arab-ar/index.html'],
				['Fulfulde', 'arab-ff/index.html'],
				['Hausa', 'arab-ha/index.html'],
				['Kashmiri', 'arab-ks/index.html'],
				['Persian', 'arab-fa/index.html'],
				['Sorani', 'arab-ckb/index.html'],
				['Uighur', 'arab-ug/index.html'],
				['Urdu', 'arab-ur/index.html'],
				['Wolofal', 'arab-wo/index.html'],
				['Pan-African', 'arab-afr/index.html'],
				['All', 'arab-all/index.html'],
				[']'],
			['• <b>Aramaic</b> ['],
				['Christian Palestinian', 'syrc-axp/index.html'],
				['Imperial','armi/index.html'],
				[']'],
			['• <b>Armenian</b> ['],
				['Armenian','armn/index.html'],
				[']'],
			['Assyrian&nbsp;Neo-Aramaic', 'syrc-aii/index.html'],
			],
	'B':[
			['<b>Balinese</b> ['],
				['Balinese','bali/index.html'],
				[']'],
			['<b>Bamum</b> ['],
				['Bamum','bamu/index.html'],
				[']'],
			['<b>Bassa Vah</b> ['],
				['Bassa','bass/index.html'],
				[']'],
			['<b>Batak</b> ['],
				['Batak','batk/index.html'],
				[']'],
			['<b>Bengali</b> ['],
				['Bangla','beng/index.html'],
				[']'],
			['<b>Buginese</b> ['],
				['Buginese','bugi/index.html'],
				[']'],
			['<b>Buhid</b> ['],
				['Buhid','buhd/index.html'],
				[']'],
			],
	'C':[
			['<b>Cherokee</b> ['],
				['Cherokee','cher/index.html'],
				[']'],
			['• <b>Chinese</b> ['],
				['ST Chinese','hani/index.html'],
				[']'],
			['• <b>Cyrillic</b> ['],
				['Mongolian', 'cyrl-mn/index.html'],
				['Russian', 'cyrl-ru/index.html'],
				['Ukrainian', 'cyrl-uk/index.html'],
				['All', 'cyrl-all/index.html'],
				[']'],
			],
	'D':[
			['<b>Devanagari</b> ['],
				['Hindi', 'deva-hi/index.html'],
				['Kashmiri', 'deva-ks/index.html'],
				['All', 'deva-all/index.html'],
				[']'],
			],
	'E':[
			['<b>Egyptian</b> ['],
				['Hieroglyphs', 'egyptian/index.html'],
				['Kashmiri', 'deva-ks/index.html'],
				['All', 'deva-all/index.html'],
				[']'],
			['• <b>Elymaic</b> ['],
				['Elymaic', 'elym/index.html'],
				[']'],
			['• <b>Ethiopic</b> ['],
				['Amharic', 'ethi-am/index.html'],
				['All', 'ethi/index.html'],
				[']'],
			  ],
	'F':[
			['<b>Fraser script</b> ['],
				['Lisu', 'lisu/index.html'],
				[']'],
			],
	'G':[
			['<b>Garay</b> ['],
				['Wolof', 'gara-wo/index.html'],
				[']'],
			['<b>Georgian</b> ['],
				['Modern', 'geor-ka/index.html'],
				['Khutsuri', 'geok-ka/index.html'],
				['All', 'geor-all/index.html'],
				[']'],
			['• <b>Glagolitic</b> ['],
				['Glagolitic', 'glag/index.html'],
				[']'],
			['• <b>Gothic</b> ['],
				['Gothic', 'goth/index.html'],
				[']'],
			['• <b>Greek</b> ['],
				['Modern', 'grek/index.html'],
				[']'],
			['• <b>Gujarati</b> ['],
				['Gujarati', 'gujr/index.html'],
				[']'],
			['• <b>Gurmukhi</b> ['],
				['Gurmukhi/Punjabi', 'guru/index.html'],
				[']'],
			],
	'H':[
			['<b>Hanifi Rohingya</b> ['],
				['Rohingya', 'rohg/index.html'],
				[']'],
			['• <b>Hanunoo</b> ['],
				['Hanunó’o', 'hano/index.html'],
				[']'],
			['• <b>Hatran</b> ['],
				['Hatran', 'hatr/index.html'],
				[']'],
			['• <b>Hebrew</b> ['],
				['Israeli Hebrew', 'hebr/index.html'],
				[']'],
			['• <b>Hmong</b> ['],
				['A-Hmao','plrd-hmd/index.html'],
				['All','plrd-all/index.html'],
				[']'],
			],
	'I':[
			['<b>IPA</b> ['],
				['Traditional chart', 'ipa/index.html'],
				['By position', 'ipa2/index.html'],
				['By type', 'ipa3/index.html'],
				[']'],
			],
	'J':[
			['<b>Japanese</b> ['],
				['Japanese', 'jpan/index.html'],
				[']'],
			['• <b>Javanese</b> ['],
				['Javanese', 'java/index.html'],
				[']'],
			],
	'K':[
			['<b>Kayah Li</b> ['],
				['Western Kayah', 'kali/index.html'],
				[']'],
			['• <b>Khmer</b> ['],
				['Khmer', 'khmr/index.html'],
				[']'],
			['• <b>Kurdish</b> ['],
				['Kurmanji', 'latn-kmr/index.html'],
				['Sorani', 'arab-ckb/index.html'],
				[']'],
			],
	'L':[
			['<b>Lanna</b> ['],
				['Northern&nbsp;Thai', 'lana-nod/index.html'],
				['Tai&nbsp;Khün', 'lana-kkh/index.html'],
				[']'],
			['• <b>Lao</b> ['],
				['Lao', 'lao/index.html'],
				[']'],
			['• <b>Latin</b> ['],
				['All Latin & diacritics','latn-all/index.html'],
				['Pan-African','latn-afr/index.html'],
				['Bamanan','latn-bm/index.html'],
				['Fula','latn-ff/index.html'],
				['Hausa Boko','latn-ha/index.html'],
				['Kurmanji','latn-kmr/index.html'],
				['Old English','latn-ang/index.html'],
				['Old Norse','latn-non/index.html'],
				['Tłı̨chǫ (Dogrib)','latn-dgr/index.html'],
				['Vietnamese','latn-vi/index.html'],
				['Wolof','latn-wo/index.html'],
				[']'],
			['• <b>Lepcha</b> ['],
				['Lepcha', 'lepc-lep/index.html'],
				[']'],
			['• <b>Limbu</b> ['],
				['Limbu', 'limb-lif/index.html'],
				[']'],
			['• <b>Lisu</b> ['],
				['Lisu', 'lisu/index.html'],
				[']'],
			['• <b>Lycian</b> ['],
				['Lycian', 'lyci/index.html'],
				[']'],
			['• <b>Lydian</b> ['],
				['Lisu', 'lydi/index.html'],
				[']'],
			],
	'M':[
			['<b>Makasar</b> ['],
				['Makasar', 'maka/index.html'],
				[']'],
			['• <b>Malayalam</b> ['],
				['Malayalam', 'mlym/index.html'],
				[']'],
			['• <b>Mandaic</b> ['],
				['Neo-Mandaic', 'mand/index.html'],
				[']'],
			['• <b>Mende Kikakui</b> ['],
				['Mende Kikakui', 'mend/index.html'],
				[']'],
			['• <b>Mongolian</b> ['],
				['Halh Mongolian', 'mong-mn/index.html'],
				[']'],
			['• <b>Myanmar</b> ['],
				['Burmese', 'mymr-my/index.html'],
				['Shan', 'mymr-shn/index.html'],
				[']'],
			['• <b>Miao</b> ['],
				['A-Hmao','plrd-hmd/index.html'],
				['All','plrd-all/index.html'],
				[']'],
			['• <b>Mro</b> ['],
				['Mru','mroo-mro/index.html'],
				[']'],
			],
	'N':[
			['<b>Nabataean</b> ['],
				['Nabataean', 'nbat/index.html'],
				[']'],
			['• <b>Nag Mundari</b> ['],
				['Mundari','nagm-unr/index.html'],
				[']'],
			['• <b>N’Ko</b> ['],
				['N’Ko','nko/index.html'],
				[']'],
			['• <b>New&nbsp;Tai&nbsp;Lü</b> ['],
				['Tai&nbsp;Lü','talu/index.html'],
				[']'],
			['• <b>Newa</b> ['],
				['Newar','newa/index.html'],
				[']'],
			],
	'O':[
			['<b>Oriya</b> ['],
				['Odia', 'orya/index.html'],
				[']'],
			['• <b>Ol Chiki</b> ['],
				['Santali','olck/index.html'],
				[']'],
			['• <b>Osage</b> ['],
				['Osage','osge/index.html'],
				[']'],
			],
	'P':[
			['<b>Palmyrene</b> ['],
				['Palmyrene', 'palm/index.html'],
				[']'],
			['• <b>Phoenician</b> ['],
				['Phoenician','phnx/index.html'],
				[']'],
			['• <b>Pahlavi</b> ['],
				['Pahlavi','phli/index.html'],
				[']'],
			['• <b>Parthian</b> ['],
				['Parthian','prti/index.html'],
				[']'],
			['• <b>Pollard&nbsp;script</b> ['],
				['A-Hmao','plrd-hmd/index.html'],
				['All','plrd-all/index.html'],
				[']'],
			],
	'R':[
			['<b>Rejang</b> ['],
				['Rejang', 'rjng/index.html'],
				[']'],
			['• <b>Runic</b> ['],
				['All','runr/index.html'],
				['Anglo-Saxon','runr-ang/index.html'],
				['Tolkien','runr-en/index.html'],
				[']'],
			],
	'S':[
			['<b>Sinhala</b> ['],
				['Sinhala', 'sinh/index.html'],
				[']'],
			['• <b>Sundanese</b> ['],
				['Sundanese','sund/index.html'],
				[']'],
			['• <b>Sunuwar</b> ['],
				['Kiranti-Kõits','sunu-suz/index.html'],
				[']'],
			['• <b>Syriac</b> ['],
				['Classic Syriac', 'syrc/index.html'],
				['Assyrian&nbsp;Neo-Aramaic', 'syrc-aii/index.html'],
				['Turoyo', 'syrc-tru/index.html'],
				['CPA', 'syrc-axp/index.html'],
				[']'],
			],
	'T':[
			['<b>Tagbanwa</b> ['],
				['Tagbanwa', 'tagb/index.html'],
				[']'],
			['• <b>Tai&nbsp;Le</b> ['],
				['Tai Nüa','tale/index.html'],
				[']'],
			['• <b>Tai Tham</b> ['],
				['Northern&nbsp;Thai', 'lana-nod/index.html'],
				['Tai&nbsp;Khün', 'lana-kkh/index.html'],
				[']'],
			['• <b>Tai&nbsp;Viet</b> ['],
				['Tai Dam','tavt/index.html'],
				[']'],
			['• <b>Tamil</b> ['],
				['Tamil','taml/index.html'],
				[']'],
			['• <b>Telugu</b> ['],
				['Telugu','telu/index.html'],
				[']'],
			['• <b>Thaana</b> ['],
				['Dhivehi','thaa/index.html'],
				[']'],
			['• <b>Thai</b> ['],
				['Thai','thai/index.html'],
				[']'],
			['• <b>Tibetan</b> ['],
				['Tibetan','tibt/index.html'],
				[']'],
			['• <b>Tifinagh</b> ['],
				['Neo-tifinagh', 'tfng-zgh/index.html'],
				['All', 'tfng-all/index.html'],
				[']'],
			],
	'U':[
			['<b>UCAS</b> ['],
				['Eastern Canadian Inuktitut', 'cans-ike/index.html'],
				['Plains Cree', 'cans-crk/index.html'],
				['All', 'cans/index.html'],
				[']'],
			['• <b>Ugaritic</b> ['],
				['Ugaritic','ugar/index.html'],
				[']'],
			],
	'V':[
			['<b>Vai</b> ['],
				['Vai', 'vai/index.html'],
				[']'],
			],
	'Y':[
			['<b>Yezidi</b> ['],
				['Yezidi', 'yezi/index.html'],
				[']'],
			],
	}
