charData["\u19B8\u19B0"]="NEW TAI LUE VOWEL SIGN OA, VOWEL SIGN VOWEL SHORTENER"
charData["\u19B2\u19B0"]="NEW TAI LUE VOWEL SIGN II, VOWEL SIGN VOWEL SHORTENER"
charData["\u1A64\u1A74"]="TAI THAM VOWEL SIGN TALL AA, SIGN MAI KANG"
charData["\u1A49\u1A60"]="TAI THAM LETTER HIGH HA, SIGN SAKOT"
charData["\u1A60\u1A45"]="TAI THAM SIGN SAKOT, LETTER WA"
charData["\u1A60\u1A3F"]="TAI THAM SIGN SAKOT, LETTER LOW YA"



