
charData["\u0995\u09CD\u09B7"]="BENGALI LETTER KA, BENGALI SIGN VIRAMA, BENGALI LETTER SSA"
charData["\u09A1\u09BC"]="BENGALI LETTER DDA, BENGALI SIGN NUKTA"
charData["\u09A2\u09BC"]="BENGALI LETTER DDHA, BENGALI SIGN NUKTA"
charData["\u09CD\u09AF"]="BENGALI SIGN VIRAMA, BENGALI LETTER YA\u200B"
charData["\u09AF\u09BC"]="BENGALI LETTER YA, BENGALI SIGN NUKTA"
