function localtranscribe (direction, str) {
	
	if (direction == 'transliterate') { return transliterate(str) }
	if (direction == 'reverse') { return reverse(str) }
	}
		
		
function transliterate (str) {
	str += '  '

str = str.toUpperCase()

str = str.replace(/Ꭰ/g, "a")
str = str.replace(/Ꭱ/g, "e")
str = str.replace(/Ꭲ/g, "i")
str = str.replace(/Ꭳ/g, "o")
str = str.replace(/Ꭴ/g, "u")
str = str.replace(/Ꭵ/g, "v")
str = str.replace(/Ꭶ/g, "ga")
str = str.replace(/Ꭷ/g, "ka")
str = str.replace(/Ꭸ/g, "ge")
str = str.replace(/Ꭹ/g, "gi")
str = str.replace(/Ꭺ/g, "go")
str = str.replace(/Ꭻ/g, "gu")
str = str.replace(/Ꭼ/g, "gv")
str = str.replace(/Ꭽ/g, "ha")
str = str.replace(/Ꭾ/g, "he")
str = str.replace(/Ꭿ/g, "hi")
str = str.replace(/Ꮀ/g, "ho")
str = str.replace(/Ꮁ/g, "hu")
str = str.replace(/Ꮂ/g, "hv")
str = str.replace(/Ꮃ/g, "la")
str = str.replace(/Ꮄ/g, "le")
str = str.replace(/Ꮅ/g, "li")
str = str.replace(/Ꮆ/g, "lo")
str = str.replace(/Ꮇ/g, "lu")
str = str.replace(/Ꮈ/g, "lv")
str = str.replace(/Ꮉ/g, "ma")
str = str.replace(/Ꮊ/g, "me")
str = str.replace(/Ꮋ/g, "mi")
str = str.replace(/Ꮌ/g, "mo")
str = str.replace(/Ꮍ/g, "mu")
str = str.replace(/Ᏽ/g, "mv")
str = str.replace(/Ꮎ/g, "na")
str = str.replace(/Ꮏ/g, "hna")
str = str.replace(/Ꮐ/g, "nah")
str = str.replace(/Ꮑ/g, "ne")
str = str.replace(/Ꮒ/g, "ni")
str = str.replace(/Ꮓ/g, "no")
str = str.replace(/Ꮔ/g, "nu")
str = str.replace(/Ꮕ/g, "nv")
str = str.replace(/Ꮖ/g, "qa")
str = str.replace(/Ꮗ/g, "qe")
str = str.replace(/Ꮘ/g, "qi")
str = str.replace(/Ꮙ/g, "qo")
str = str.replace(/Ꮚ/g, "qu")
str = str.replace(/Ꮛ/g, "qv")
str = str.replace(/Ꮝ/g, "s")
str = str.replace(/Ꮜ/g, "sa")
str = str.replace(/Ꮞ/g, "se")
str = str.replace(/Ꮟ/g, "si")
str = str.replace(/Ꮠ/g, "so")
str = str.replace(/Ꮡ/g, "su")
str = str.replace(/Ꮢ/g, "sv")
str = str.replace(/Ꮣ/g, "da")
str = str.replace(/Ꮤ/g, "ta")
str = str.replace(/Ꮥ/g, "de")
str = str.replace(/Ꮦ/g, "te")
str = str.replace(/Ꮧ/g, "di")
str = str.replace(/Ꮨ/g, "ti")
str = str.replace(/Ꮩ/g, "do")
str = str.replace(/Ꮪ/g, "du")
str = str.replace(/Ꮫ/g, "dv")
str = str.replace(/Ꮬ/g, "dla")
str = str.replace(/Ꮭ/g, "tla")
str = str.replace(/Ꮮ/g, "dle")
str = str.replace(/Ꮯ/g, "dli")
str = str.replace(/Ꮰ/g, "dlo")
str = str.replace(/Ꮱ/g, "dlu")
str = str.replace(/Ꮲ/g, "dlv")
str = str.replace(/Ꮳ/g, "tsa")
str = str.replace(/Ꮴ/g, "tse")
str = str.replace(/Ꮵ/g, "tsi")
str = str.replace(/Ꮶ/g, "tso")
str = str.replace(/Ꮷ/g, "tsu")
str = str.replace(/Ꮸ/g, "tsv")
str = str.replace(/Ꮹ/g, "wa")
str = str.replace(/Ꮺ/g, "we")
str = str.replace(/Ꮻ/g, "wi")
str = str.replace(/Ꮼ/g, "wo")
str = str.replace(/Ꮽ/g, "wu")
str = str.replace(/Ꮾ/g, "wv")
str = str.replace(/Ꮿ/g, "ya")
str = str.replace(/Ᏸ/g, "ye")
str = str.replace(/Ᏹ/g, "yi")
str = str.replace(/Ᏺ/g, "yo")
str = str.replace(/Ᏻ/g, "yu")
str = str.replace(/Ᏼ/g, "yv")

	return str.trim()
	}



function reverse (str) {
	str += '  '

str = str.replace(/yv/g, "Ᏼ")
str = str.replace(/yu/g, "Ᏻ")
str = str.replace(/yo/g, "Ᏺ")
str = str.replace(/yi/g, "Ᏹ")
str = str.replace(/ye/g, "Ᏸ")
str = str.replace(/ya/g, "Ꮿ")
str = str.replace(/wv/g, "Ꮾ")
str = str.replace(/wu/g, "Ꮽ")
str = str.replace(/wo/g, "Ꮼ")
str = str.replace(/wi/g, "Ꮻ")
str = str.replace(/we/g, "Ꮺ")
str = str.replace(/wa/g, "Ꮹ")
str = str.replace(/tsv/g, "Ꮸ")
str = str.replace(/tsu/g, "Ꮷ")
str = str.replace(/tso/g, "Ꮶ")
str = str.replace(/tsi/g, "Ꮵ")
str = str.replace(/tse/g, "Ꮴ")
str = str.replace(/tsa/g, "Ꮳ")
str = str.replace(/dlv/g, "Ꮲ")
str = str.replace(/dlu/g, "Ꮱ")
str = str.replace(/dlo/g, "Ꮰ")
str = str.replace(/dli/g, "Ꮯ")
str = str.replace(/dle/g, "Ꮮ")
str = str.replace(/tla/g, "Ꮭ")
str = str.replace(/dla/g, "Ꮬ")
str = str.replace(/dv/g, "Ꮫ")
str = str.replace(/du/g, "Ꮪ")
str = str.replace(/do/g, "Ꮩ")
str = str.replace(/ti/g, "Ꮨ")
str = str.replace(/di/g, "Ꮧ")
str = str.replace(/te/g, "Ꮦ")
str = str.replace(/de/g, "Ꮥ")
str = str.replace(/ta/g, "Ꮤ")
str = str.replace(/da/g, "Ꮣ")
str = str.replace(/sv/g, "Ꮢ")
str = str.replace(/su/g, "Ꮡ")
str = str.replace(/so/g, "Ꮠ")
str = str.replace(/si/g, "Ꮟ")
str = str.replace(/se/g, "Ꮞ")
str = str.replace(/sa/g, "Ꮜ")
str = str.replace(/s/g, "Ꮝ")
str = str.replace(/qv/g, "Ꮛ")
str = str.replace(/qu/g, "Ꮚ")
str = str.replace(/qo/g, "Ꮙ")
str = str.replace(/qi/g, "Ꮘ")
str = str.replace(/qe/g, "Ꮗ")
str = str.replace(/qa/g, "Ꮖ")
str = str.replace(/nv/g, "Ꮕ")
str = str.replace(/nu/g, "Ꮔ")
str = str.replace(/no/g, "Ꮓ")
str = str.replace(/ni/g, "Ꮒ")
str = str.replace(/ne/g, "Ꮑ")
str = str.replace(/nah/g, "Ꮐ")
str = str.replace(/hna/g, "Ꮏ")
str = str.replace(/na/g, "Ꮎ")
str = str.replace(/mv/g, "Ᏽ")
str = str.replace(/mu/g, "Ꮍ")
str = str.replace(/mo/g, "Ꮌ")
str = str.replace(/mi/g, "Ꮋ")
str = str.replace(/me/g, "Ꮊ")
str = str.replace(/ma/g, "Ꮉ")
str = str.replace(/lv/g, "Ꮈ")
str = str.replace(/lu/g, "Ꮇ")
str = str.replace(/lo/g, "Ꮆ")
str = str.replace(/li/g, "Ꮅ")
str = str.replace(/le/g, "Ꮄ")
str = str.replace(/la/g, "Ꮃ")
str = str.replace(/hv/g, "Ꮂ")
str = str.replace(/hu/g, "Ꮁ")
str = str.replace(/ho/g, "Ꮀ")
str = str.replace(/hi/g, "Ꭿ")
str = str.replace(/he/g, "Ꭾ")
str = str.replace(/ha/g, "Ꭽ")
str = str.replace(/gv/g, "Ꭼ")
str = str.replace(/gu/g, "Ꭻ")
str = str.replace(/go/g, "Ꭺ")
str = str.replace(/gi/g, "Ꭹ")
str = str.replace(/ge/g, "Ꭸ")
str = str.replace(/ka/g, "Ꭷ")
str = str.replace(/ga/g, "Ꭶ")
str = str.replace(/v/g, "Ꭵ")
str = str.replace(/u/g, "Ꭴ")
str = str.replace(/o/g, "Ꭳ")
str = str.replace(/i/g, "Ꭲ")
str = str.replace(/e/g, "Ꭱ")
str = str.replace(/a/g, "Ꭰ")


	return str.trim()
	}



