charData["\u1B44\u1B0B"]="BALINESE ADEG ADEG, BALINESE LETTER RA REPA200B"
charData["\u1B44\u1B0C"]="BALINESE ADEG ADEG, BALINESE LETTER RA REPA TEDUNG200B"

charData["\u1B1A\u1B34"]="BALINESE LETTER JA, BALINESE SIGN REREKAN"
charData["\u1B27\u1B34"]="BALINESE LETTER PA, BALINESE SIGN REREKAN"
charData["\u1B2F\u1B34"]="BALINESE LETTER WA, BALINESE SIGN REREKAN"
charData["\u1B13\u1B34"]="BALINESE LETTER KA, BALINESE SIGN REREKAN"
charData["\u1B33\u1B34"]="BALINESE LETTER HA, BALINESE SIGN REREKAN"
charData["\u1B15\u1B34"]="BALINESE LETTER GA, BALINESE SIGN REREKAN"
charData["\u1B17\u1B34"]="BALINESE LETTER NGA, BALINESE SIGN REREKAN"

