charData["\u1A63\u1A74"]="TAI THAM VOWEL SIGN AA, SIGN MAI KANG"
charData["\u1A64\u1A74"]="TAI THAM VOWEL SIGN TALL AA, SIGN MAI KANG"
charData["\u1A49\u1A60"]="TAI THAM LETTER HIGH HA, SIGN SAKOT"
charData["\u1A60\u1A45"]="TAI THAM SIGN SAKOT, LETTER WA"
charData["\u1A60\u1A3F"]="TAI THAM SIGN SAKOT, LETTER LOW YA"


charData["\u1A49\u1A60\u1A26"]="TAI THAM LETTER HIGH HA, SIGN SAKOT, LETTER NGA"
charData["\u1A49\u1A60\u1A2C"]="TAI THAM LETTER HIGH HA, SIGN SAKOT, LETTER NYA"
charData["\u1A49\u1A60\u1A36"]="TAI THAM LETTER HIGH HA, SIGN SAKOT, LETTER NA"
charData["\u1A49\u1A60\u1A3E"]="TAI THAM LETTER HIGH HA, SIGN SAKOT, LETTER MA"
charData["\u1A49\u1A55"]="TAI THAM LETTER HIGH HA, CONSONANT SIGN MEDIAL RA"
charData["\u1A49\u1A60\u1A45"]="TAI THAM LETTER HIGH HA, SIGN SAKOT, LETTER WA"

charData["\u1A2D\u1A5B"]="TAI THAM LETTER RATA, CONSONANT SIGN HIGH RATHA OR LOW PA"



