charData["\u004E\u0047"]="LATIN CAPITAL LETTER N, LATIN CAPITAL LETTER G"
charData["\u006E\u0067"]="LATIN SMALL LETTER N, LATIN SMALL LETTER G"

charData["\u02E9\u02E5"]="MODIFIER LETTER EXTRA-LOW TONE BAR, MODIFIER LETTER EXTRA-HIGH TONE BAR"
charData["\u02E5\u02E9"]="MODIFIER LETTER EXTRA-HIGH TONE BAR, MODIFIER LETTER EXTRA-LOW TONE BAR"
charData["\u02E6\u02E5"]="MODIFIER LETTER HIGH TONE BAR, MODIFIER LETTER EXTRA-HIGH TONE BAR"
charData["\u02E9\u02E8"]="MODIFIER LETTER EXTRA-LOW TONE BAR, MODIFIER LETTER LOW TONE BAR"
charData["\u02E7\u02E6\u02E7"]="MODIFIER LETTER MID TONE BAR, MODIFIER LETTER HIGH TONE BAR, MODIFIER LETTER MID TONE BAR"
