globals.showLOCTrans = ''
globals.showTransliteration = ''
globals.showIPATrans = ''
globals.typeAssist = ''
globals.showKeysTranslitToggle = false

function localInitialise () {

	}



window.charCheckerList = [

// Presentation forms A
{ wrong:"ﭐ", right:"ٱ" },
{ wrong:"ﭑ", right:"ٱ" },
{ wrong:"ﭒ", right:"ٻ" },
{ wrong:"ﭓ", right:"ٻ" },
{ wrong:"ﭔ", right:"ٻ" },
{ wrong:"ﭕ", right:"ٻ" },
{ wrong:"ﭖ", right:"پ" },
{ wrong:"ﭗ", right:"پ" },
{ wrong:"ﭘ", right:"پ" },
{ wrong:"ﭙ", right:"پ" },
{ wrong:"ﭚ", right:"ڀ" },
{ wrong:"ﭛ", right:"ڀ" },
{ wrong:"ﭜ", right:"ڀ" },
{ wrong:"ﭝ", right:"ڀ" },
{ wrong:"ﭞ", right:"ٺ" },
{ wrong:"ﭟ", right:"ٺ" },
{ wrong:"ﭠ", right:"ٺ" },
{ wrong:"ﭡ", right:"ٺ" },
{ wrong:"ﭢ", right:"ٿ" },
{ wrong:"ﭣ", right:"ٿ" },
{ wrong:"ﭤ", right:"ٿ" },
{ wrong:"ﭥ", right:"ٿ" },
{ wrong:"ﭦ", right:"ٹ" },
{ wrong:"ﭧ", right:"ٹ" },
{ wrong:"ﭨ", right:"ٹ" },
{ wrong:"ﭩ", right:"ٹ" },
{ wrong:"ﭪ", right:"ڤ" },
{ wrong:"ﭫ", right:"ڤ" },
{ wrong:"ﭬ", right:"ڤ" },
{ wrong:"ﭭ", right:"ڤ" },
{ wrong:"ﭮ", right:"ڦ" },
{ wrong:"ﭯ", right:"ڦ" },
{ wrong:"ﭰ", right:"ڦ" },
{ wrong:"ﭱ", right:"ڦ" },
{ wrong:"ﭲ", right:"ڄ" },
{ wrong:"ﭳ", right:"ڄ" },
{ wrong:"ﭴ", right:"ڄ" },
{ wrong:"ﭵ", right:"ڄ" },
{ wrong:"ﭶ", right:"ڃ" },
{ wrong:"ﭷ", right:"ڃ" },
{ wrong:"ﭸ", right:"ڃ" },
{ wrong:"ﭹ", right:"ڃ" },
{ wrong:"ﭺ", right:"چ" },
{ wrong:"ﭻ", right:"چ" },
{ wrong:"ﭼ", right:"چ" },
{ wrong:"ﭽ", right:"چ" },
{ wrong:"ﭾ", right:"ڇ" },
{ wrong:"ﭿ", right:"ڇ" },
{ wrong:"ﮀ", right:"ڇ" },
{ wrong:"ﮁ", right:"ڇ" },
{ wrong:"ﮂ", right:"ڍ" },
{ wrong:"ﮃ", right:"ڍ" },
{ wrong:"ﮄ", right:"ڌ" },
{ wrong:"ﮅ", right:"ڌ" },
{ wrong:"ﮆ", right:"ڎ" },
{ wrong:"ﮇ", right:"ڎ" },
{ wrong:"ﮈ", right:"ڈ" },
{ wrong:"ﮉ", right:"ڈ" },
{ wrong:"ﮊ", right:"ژ" },
{ wrong:"ﮋ", right:"ژ" },
{ wrong:"ﮌ", right:"ڑ" },
{ wrong:"ﮍ", right:"ڑ" },
{ wrong:"ﮎ", right:"ک" },
{ wrong:"ﮏ", right:"ک" },
{ wrong:"ﮐ", right:"ک" },
{ wrong:"ﮑ", right:"ک" },
{ wrong:"ﮒ", right:"گ" },
{ wrong:"ﮓ", right:"گ" },
{ wrong:"ﮔ", right:"گ" },
{ wrong:"ﮕ", right:"گ" },
{ wrong:"ﮖ", right:"ڳ" },
{ wrong:"ﮗ", right:"ڳ" },
{ wrong:"ﮘ", right:"ڳ" },
{ wrong:"ﮙ", right:"ڳ" },
{ wrong:"ﮚ", right:"ڱ" },
{ wrong:"ﮛ", right:"ڱ" },
{ wrong:"ﮜ", right:"ڱ" },
{ wrong:"ﮝ", right:"ڱ" },
{ wrong:"ﮞ", right:"ں" },
{ wrong:"ﮟ", right:"ں" },
{ wrong:"ﮠ", right:"ڻ" },
{ wrong:"ﮡ", right:"ڻ" },
{ wrong:"ﮢ", right:"ڻ" },
{ wrong:"ﮣ", right:"ڻ" },
{ wrong:"ﮤ", right:"ۀ" },
{ wrong:"ﮥ", right:"ۀ" },
{ wrong:"ﮦ", right:"ہ" },
{ wrong:"ﮧ", right:"ہ" },
{ wrong:"ﮨ", right:"ہ" },
{ wrong:"ﮩ", right:"ہ" },
{ wrong:"ﮪ", right:"ھ" },
{ wrong:"ﮫ", right:"ھ" },
{ wrong:"ﮬ", right:"ھ" },
{ wrong:"ﮭ", right:"ھ" },
{ wrong:"ﮮ", right:"ے" },
{ wrong:"ﮯ", right:"ے" },
{ wrong:"ﮰ", right:"ۓ" },
{ wrong:"ﮱ", right:"ۓ" },
{ wrong:"ﯓ", right:"ڭ" },
{ wrong:"ﯔ", right:"ڭ" },
{ wrong:"ﯕ", right:"ڭ" },
{ wrong:"ﯖ", right:"ڭ" },
{ wrong:"ﯗ", right:"ۇ" },
{ wrong:"ﯘ", right:"ۇ" },
{ wrong:"ﯙ", right:"ۆ" },
{ wrong:"ﯚ", right:"ۆ" },
{ wrong:"ﯛ", right:"ۈ" },
{ wrong:"ﯜ", right:"ۈ" },
{ wrong:"ﯝ", right:"ۇٴ" },
{ wrong:"ﯞ", right:"ۋ" },
{ wrong:"ﯟ", right:"ۋ" },
{ wrong:"ﯠ", right:"ۅ" },
{ wrong:"ﯡ", right:"ۅ" },
{ wrong:"ﯢ", right:"ۉ" },
{ wrong:"ﯣ", right:"ۉ" },
{ wrong:"ﯤ", right:"ې" },
{ wrong:"ﯥ", right:"ې" },
{ wrong:"ﯦ", right:"ې" },
{ wrong:"ﯧ", right:"ې" },
{ wrong:"ﯨ", right:"ى" },
{ wrong:"ﯩ", right:"ى" },
{ wrong:"ﯪ", right:"ئا" },
{ wrong:"ﯫ", right:"ئا" },
{ wrong:"ﯬ", right:"ئە" },
{ wrong:"ﯭ", right:"ئە" },
{ wrong:"ﯮ", right:"ئو" },
{ wrong:"ﯯ", right:"ئو" },
{ wrong:"ﯰ", right:"ئۇ" },
{ wrong:"ﯱ", right:"ئۇ" },
{ wrong:"ﯲ", right:"ئۆ" },
{ wrong:"ﯳ", right:"ئۆ" },
{ wrong:"ﯴ", right:"ئۈ" },
{ wrong:"ﯵ", right:"ئۈ" },
{ wrong:"ﯶ", right:"ئې" },
{ wrong:"ﯷ", right:"ئې" },
{ wrong:"ﯸ", right:"ئې" },
{ wrong:"ﯹ", right:"ئى" },
{ wrong:"ﯺ", right:"ئى" },
{ wrong:"ﯻ", right:"ئى" },
{ wrong:"ﯼ", right:"ی" },
{ wrong:"ﯽ", right:"ی" },
{ wrong:"ﯾ", right:"ی" },
{ wrong:"ﯿ", right:"ی" },
{ wrong:"ﰀ", right:"ئج" },
{ wrong:"ﰁ", right:"ئح" },
{ wrong:"ﰂ", right:"ئم" },
{ wrong:"ﰃ", right:"ئى" },
{ wrong:"ﰄ", right:"ئي" },
{ wrong:"ﰅ", right:"بج" },
{ wrong:"ﰆ", right:"بح" },
{ wrong:"ﰇ", right:"بخ" },
{ wrong:"ﰈ", right:"بم" },
{ wrong:"ﰉ", right:"بى" },
{ wrong:"ﰊ", right:"بي" },
{ wrong:"ﰋ", right:"تج" },
{ wrong:"ﰌ", right:"تح" },
{ wrong:"ﰍ", right:"تخ" },
{ wrong:"ﰎ", right:"تم" },
{ wrong:"ﰏ", right:"تى" },
{ wrong:"ﰐ", right:"تي" },
{ wrong:"ﰑ", right:"ثج" },
{ wrong:"ﰒ", right:"ثم" },
{ wrong:"ﰓ", right:"ثى" },
{ wrong:"ﰔ", right:"ثي" },
{ wrong:"ﰕ", right:"جح" },
{ wrong:"ﰖ", right:"جم" },
{ wrong:"ﰗ", right:"حج" },
{ wrong:"ﰘ", right:"حم" },
{ wrong:"ﰙ", right:"خج" },
{ wrong:"ﰚ", right:"خح" },
{ wrong:"ﰛ", right:"خم" },
{ wrong:"ﰜ", right:"سج" },
{ wrong:"ﰝ", right:"سح" },
{ wrong:"ﰞ", right:"سخ" },
{ wrong:"ﰟ", right:"سم" },
{ wrong:"ﰠ", right:"صح" },
{ wrong:"ﰡ", right:"صم" },
{ wrong:"ﰢ", right:"ضج" },
{ wrong:"ﰣ", right:"ضح" },
{ wrong:"ﰤ", right:"ضخ" },
{ wrong:"ﰥ", right:"ضم" },
{ wrong:"ﰦ", right:"طح" },
{ wrong:"ﰧ", right:"طم" },
{ wrong:"ﰨ", right:"ظم" },
{ wrong:"ﰩ", right:"عج" },
{ wrong:"ﰪ", right:"عم" },
{ wrong:"ﰫ", right:"غج" },
{ wrong:"ﰬ", right:"غم" },
{ wrong:"ﰭ", right:"فج" },
{ wrong:"ﰮ", right:"فح" },
{ wrong:"ﰯ", right:"فخ" },
{ wrong:"ﰰ", right:"فم" },
{ wrong:"ﰱ", right:"فى" },
{ wrong:"ﰲ", right:"في" },
{ wrong:"ﰳ", right:"قح" },
{ wrong:"ﰴ", right:"قم" },
{ wrong:"ﰵ", right:"قى" },
{ wrong:"ﰶ", right:"قي" },
{ wrong:"ﰷ", right:"كا" },
{ wrong:"ﰸ", right:"كج" },
{ wrong:"ﰹ", right:"كح" },
{ wrong:"ﰺ", right:"كخ" },
{ wrong:"ﰻ", right:"كل" },
{ wrong:"ﰼ", right:"كم" },
{ wrong:"ﰽ", right:"كى" },
{ wrong:"ﰾ", right:"كي" },
{ wrong:"ﰿ", right:"لج" },
{ wrong:"ﱀ", right:"لح" },
{ wrong:"ﱁ", right:"لخ" },
{ wrong:"ﱂ", right:"لم" },
{ wrong:"ﱃ", right:"لى" },
{ wrong:"ﱄ", right:"لي" },
{ wrong:"ﱅ", right:"مج" },
{ wrong:"ﱆ", right:"مح" },
{ wrong:"ﱇ", right:"مخ" },
{ wrong:"ﱈ", right:"مم" },
{ wrong:"ﱉ", right:"مى" },
{ wrong:"ﱊ", right:"مي" },
{ wrong:"ﱋ", right:"نج" },
{ wrong:"ﱌ", right:"نح" },
{ wrong:"ﱍ", right:"نخ" },
{ wrong:"ﱎ", right:"نم" },
{ wrong:"ﱏ", right:"نى" },
{ wrong:"ﱐ", right:"ني" },
{ wrong:"ﱑ", right:"هج" },
{ wrong:"ﱒ", right:"هم" },
{ wrong:"ﱓ", right:"هى" },
{ wrong:"ﱔ", right:"هي" },
{ wrong:"ﱕ", right:"يج" },
{ wrong:"ﱖ", right:"يح" },
{ wrong:"ﱗ", right:"يخ" },
{ wrong:"ﱘ", right:"يم" },
{ wrong:"ﱙ", right:"يى" },
{ wrong:"ﱚ", right:"يي" },
{ wrong:"ﱛ", right:"ذٰ" },
{ wrong:"ﱜ", right:"رٰ" },
{ wrong:"ﱝ", right:"ىٰ" },
{ wrong:"ﱞ", right:" ٌّ" },
{ wrong:"ﱟ", right:" ٍّ" },
{ wrong:"ﱠ", right:" َّ" },
{ wrong:"ﱡ", right:" ُّ" },
{ wrong:"ﱢ", right:" ِّ" },
{ wrong:"ﱣ", right:" ّٰ" },
{ wrong:"ﱤ", right:"ئر" },
{ wrong:"ﱥ", right:"ئز" },
{ wrong:"ﱦ", right:"ئم" },
{ wrong:"ﱧ", right:"ئن" },
{ wrong:"ﱨ", right:"ئى" },
{ wrong:"ﱩ", right:"ئي" },
{ wrong:"ﱪ", right:"بر" },
{ wrong:"ﱫ", right:"بز" },
{ wrong:"ﱬ", right:"بم" },
{ wrong:"ﱭ", right:"بن" },
{ wrong:"ﱮ", right:"بى" },
{ wrong:"ﱯ", right:"بي" },
{ wrong:"ﱰ", right:"تر" },
{ wrong:"ﱱ", right:"تز" },
{ wrong:"ﱲ", right:"تم" },
{ wrong:"ﱳ", right:"تن" },
{ wrong:"ﱴ", right:"تى" },
{ wrong:"ﱵ", right:"تي" },
{ wrong:"ﱶ", right:"ثر" },
{ wrong:"ﱷ", right:"ثز" },
{ wrong:"ﱸ", right:"ثم" },
{ wrong:"ﱹ", right:"ثن" },
{ wrong:"ﱺ", right:"ثى" },
{ wrong:"ﱻ", right:"ثي" },
{ wrong:"ﱼ", right:"فى" },
{ wrong:"ﱽ", right:"في" },
{ wrong:"ﱾ", right:"قى" },
{ wrong:"ﱿ", right:"قي" },
{ wrong:"ﲀ", right:"كا" },
{ wrong:"ﲁ", right:"كل" },
{ wrong:"ﲂ", right:"كم" },
{ wrong:"ﲃ", right:"كى" },
{ wrong:"ﲄ", right:"كي" },
{ wrong:"ﲅ", right:"لم" },
{ wrong:"ﲆ", right:"لى" },
{ wrong:"ﲇ", right:"لي" },
{ wrong:"ﲈ", right:"ما" },
{ wrong:"ﲉ", right:"مم" },
{ wrong:"ﲊ", right:"نر" },
{ wrong:"ﲋ", right:"نز" },
{ wrong:"ﲌ", right:"نم" },
{ wrong:"ﲍ", right:"نن" },
{ wrong:"ﲎ", right:"نى" },
{ wrong:"ﲏ", right:"ني" },
{ wrong:"ﲐ", right:"ىٰ" },
{ wrong:"ﲑ", right:"ير" },
{ wrong:"ﲒ", right:"يز" },
{ wrong:"ﲓ", right:"يم" },
{ wrong:"ﲔ", right:"ين" },
{ wrong:"ﲕ", right:"يى" },
{ wrong:"ﲖ", right:"يي" },
{ wrong:"ﲗ", right:"ئج" },
{ wrong:"ﲘ", right:"ئح" },
{ wrong:"ﲙ", right:"ئخ" },
{ wrong:"ﲚ", right:"ئم" },
{ wrong:"ﲛ", right:"ئه" },
{ wrong:"ﲜ", right:"بج" },
{ wrong:"ﲝ", right:"بح" },
{ wrong:"ﲞ", right:"بخ" },
{ wrong:"ﲟ", right:"بم" },
{ wrong:"ﲠ", right:"به" },
{ wrong:"ﲡ", right:"تج" },
{ wrong:"ﲢ", right:"تح" },
{ wrong:"ﲣ", right:"تخ" },
{ wrong:"ﲤ", right:"تم" },
{ wrong:"ﲥ", right:"ته" },
{ wrong:"ﲦ", right:"ثم" },
{ wrong:"ﲧ", right:"جح" },
{ wrong:"ﲨ", right:"جم" },
{ wrong:"ﲩ", right:"حج" },
{ wrong:"ﲪ", right:"حم" },
{ wrong:"ﲫ", right:"خج" },
{ wrong:"ﲬ", right:"خم" },
{ wrong:"ﲭ", right:"سج" },
{ wrong:"ﲮ", right:"سح" },
{ wrong:"ﲯ", right:"سخ" },
{ wrong:"ﲰ", right:"سم" },
{ wrong:"ﲱ", right:"صح" },
{ wrong:"ﲲ", right:"صخ" },
{ wrong:"ﲳ", right:"صم" },
{ wrong:"ﲴ", right:"ضج" },
{ wrong:"ﲵ", right:"ضح" },
{ wrong:"ﲶ", right:"ضخ" },
{ wrong:"ﲷ", right:"ضم" },
{ wrong:"ﲸ", right:"طح" },
{ wrong:"ﲹ", right:"ظم" },
{ wrong:"ﲺ", right:"عج" },
{ wrong:"ﲻ", right:"عم" },
{ wrong:"ﲼ", right:"غج" },
{ wrong:"ﲽ", right:"غم" },
{ wrong:"ﲾ", right:"فج" },
{ wrong:"ﲿ", right:"فح" },
{ wrong:"ﳀ", right:"فخ" },
{ wrong:"ﳁ", right:"فم" },
{ wrong:"ﳂ", right:"قح" },
{ wrong:"ﳃ", right:"قم" },
{ wrong:"ﳄ", right:"كج" },
{ wrong:"ﳅ", right:"كح" },
{ wrong:"ﳆ", right:"كخ" },
{ wrong:"ﳇ", right:"كل" },
{ wrong:"ﳈ", right:"كم" },
{ wrong:"ﳉ", right:"لج" },
{ wrong:"ﳊ", right:"لح" },
{ wrong:"ﳋ", right:"لخ" },
{ wrong:"ﳌ", right:"لم" },
{ wrong:"ﳍ", right:"له" },
{ wrong:"ﳎ", right:"مج" },
{ wrong:"ﳏ", right:"مح" },
{ wrong:"ﳐ", right:"مخ" },
{ wrong:"ﳑ", right:"مم" },
{ wrong:"ﳒ", right:"نج" },
{ wrong:"ﳓ", right:"نح" },
{ wrong:"ﳔ", right:"نخ" },
{ wrong:"ﳕ", right:"نم" },
{ wrong:"ﳖ", right:"نه" },
{ wrong:"ﳗ", right:"هج" },
{ wrong:"ﳘ", right:"هم" },
{ wrong:"ﳙ", right:"هٰ" },
{ wrong:"ﳚ", right:"يج" },
{ wrong:"ﳛ", right:"يح" },
{ wrong:"ﳜ", right:"يخ" },
{ wrong:"ﳝ", right:"يم" },
{ wrong:"ﳞ", right:"يه" },
{ wrong:"ﳟ", right:"ئم" },
{ wrong:"ﳠ", right:"ئه" },
{ wrong:"ﳡ", right:"بم" },
{ wrong:"ﳢ", right:"به" },
{ wrong:"ﳣ", right:"تم" },
{ wrong:"ﳤ", right:"ته" },
{ wrong:"ﳥ", right:"ثم" },
{ wrong:"ﳦ", right:"ثه" },
{ wrong:"ﳧ", right:"سم" },
{ wrong:"ﳨ", right:"سه" },
{ wrong:"ﳩ", right:"شم" },
{ wrong:"ﳪ", right:"شه" },
{ wrong:"ﳫ", right:"كل" },
{ wrong:"ﳬ", right:"كم" },
{ wrong:"ﳭ", right:"لم" },
{ wrong:"ﳮ", right:"نم" },
{ wrong:"ﳯ", right:"نه" },
{ wrong:"ﳰ", right:"يم" },
{ wrong:"ﳱ", right:"يه" },
{ wrong:"ﳲ", right:"ـَّ" },
{ wrong:"ﳳ", right:"ـُّ" },
{ wrong:"ﳴ", right:"ـِّ" },
{ wrong:"ﳵ", right:"طى" },
{ wrong:"ﳶ", right:"طي" },
{ wrong:"ﳷ", right:"عى" },
{ wrong:"ﳸ", right:"عي" },
{ wrong:"ﳹ", right:"غى" },
{ wrong:"ﳺ", right:"غي" },
{ wrong:"ﳻ", right:"سى" },
{ wrong:"ﳼ", right:"سي" },
{ wrong:"ﳽ", right:"شى" },
{ wrong:"ﳾ", right:"شي" },
{ wrong:"ﳿ", right:"حى" },
{ wrong:"ﴀ", right:"حي" },
{ wrong:"ﴁ", right:"جى" },
{ wrong:"ﴂ", right:"جي" },
{ wrong:"ﴃ", right:"خى" },
{ wrong:"ﴄ", right:"خي" },
{ wrong:"ﴅ", right:"صى" },
{ wrong:"ﴆ", right:"صي" },
{ wrong:"ﴇ", right:"ضى" },
{ wrong:"ﴈ", right:"ضي" },
{ wrong:"ﴉ", right:"شج" },
{ wrong:"ﴊ", right:"شح" },
{ wrong:"ﴋ", right:"شخ" },
{ wrong:"ﴌ", right:"شم" },
{ wrong:"ﴍ", right:"شر" },
{ wrong:"ﴎ", right:"سر" },
{ wrong:"ﴏ", right:"صر" },
{ wrong:"ﴐ", right:"ضر" },
{ wrong:"ﴑ", right:"طى" },
{ wrong:"ﴒ", right:"طي" },
{ wrong:"ﴓ", right:"عى" },
{ wrong:"ﴔ", right:"عي" },
{ wrong:"ﴕ", right:"غى" },
{ wrong:"ﴖ", right:"غي" },
{ wrong:"ﴗ", right:"سى" },
{ wrong:"ﴘ", right:"سي" },
{ wrong:"ﴙ", right:"شى" },
{ wrong:"ﴚ", right:"شي" },
{ wrong:"ﴛ", right:"حى" },
{ wrong:"ﴜ", right:"حي" },
{ wrong:"ﴝ", right:"جى" },
{ wrong:"ﴞ", right:"جي" },
{ wrong:"ﴟ", right:"خى" },
{ wrong:"ﴠ", right:"خي" },
{ wrong:"ﴡ", right:"صى" },
{ wrong:"ﴢ", right:"صي" },
{ wrong:"ﴣ", right:"ضى" },
{ wrong:"ﴤ", right:"ضي" },
{ wrong:"ﴥ", right:"شج" },
{ wrong:"ﴦ", right:"شح" },
{ wrong:"ﴧ", right:"شخ" },
{ wrong:"ﴨ", right:"شم" },
{ wrong:"ﴩ", right:"شر" },
{ wrong:"ﴪ", right:"سر" },
{ wrong:"ﴫ", right:"صر" },
{ wrong:"ﴬ", right:"ضر" },
{ wrong:"ﴭ", right:"شج" },
{ wrong:"ﴮ", right:"شح" },
{ wrong:"ﴯ", right:"شخ" },
{ wrong:"ﴰ", right:"شم" },
{ wrong:"ﴱ", right:"سه" },
{ wrong:"ﴲ", right:"شه" },
{ wrong:"ﴳ", right:"طم" },
{ wrong:"ﴴ", right:"سج" },
{ wrong:"ﴵ", right:"سح" },
{ wrong:"ﴶ", right:"سخ" },
{ wrong:"ﴷ", right:"شج" },
{ wrong:"ﴸ", right:"شح" },
{ wrong:"ﴹ", right:"شخ" },
{ wrong:"ﴺ", right:"طم" },
{ wrong:"ﴻ", right:"ظم" },
{ wrong:"ﴼ", right:"اً" },
{ wrong:"ﴽ", right:"اً" },
{ wrong:"ﵐ", right:"تجم" },
{ wrong:"ﵑ", right:"تحج" },
{ wrong:"ﵒ", right:"تحج" },
{ wrong:"ﵓ", right:"تحم" },
{ wrong:"ﵔ", right:"تخم" },
{ wrong:"ﵕ", right:"تمج" },
{ wrong:"ﵖ", right:"تمح" },
{ wrong:"ﵗ", right:"تمخ" },
{ wrong:"ﵘ", right:"جمح" },
{ wrong:"ﵙ", right:"جمح" },
{ wrong:"ﵚ", right:"حمي" },
{ wrong:"ﵛ", right:"حمى" },
{ wrong:"ﵜ", right:"سحج" },
{ wrong:"ﵝ", right:"سجح" },
{ wrong:"ﵞ", right:"سجى" },
{ wrong:"ﵟ", right:"سمح" },
{ wrong:"ﵠ", right:"سمح" },
{ wrong:"ﵡ", right:"سمج" },
{ wrong:"ﵢ", right:"سمم" },
{ wrong:"ﵣ", right:"سمم" },
{ wrong:"ﵤ", right:"صحح" },
{ wrong:"ﵥ", right:"صحح" },
{ wrong:"ﵦ", right:"صمم" },
{ wrong:"ﵧ", right:"شحم" },
{ wrong:"ﵨ", right:"شحم" },
{ wrong:"ﵩ", right:"شجي" },
{ wrong:"ﵪ", right:"شمخ" },
{ wrong:"ﵫ", right:"شمخ" },
{ wrong:"ﵬ", right:"شمم" },
{ wrong:"ﵭ", right:"شمم" },
{ wrong:"ﵮ", right:"ضحى" },
{ wrong:"ﵯ", right:"ضخم" },
{ wrong:"ﵰ", right:"ضخم" },
{ wrong:"ﵱ", right:"طمح" },
{ wrong:"ﵲ", right:"طمح" },
{ wrong:"ﵳ", right:"طمم" },
{ wrong:"ﵴ", right:"طمي" },
{ wrong:"ﵵ", right:"عجم" },
{ wrong:"ﵶ", right:"عمم" },
{ wrong:"ﵷ", right:"عمم" },
{ wrong:"ﵸ", right:"عمى" },
{ wrong:"ﵹ", right:"غمم" },
{ wrong:"ﵺ", right:"غمي" },
{ wrong:"ﵻ", right:"غمى" },
{ wrong:"ﵼ", right:"فخم" },
{ wrong:"ﵽ", right:"فخم" },
{ wrong:"ﵾ", right:"قمح" },
{ wrong:"ﵿ", right:"قمم" },
{ wrong:"ﶀ", right:"لحم" },
{ wrong:"ﶁ", right:"لحي" },
{ wrong:"ﶂ", right:"لحى" },
{ wrong:"ﶃ", right:"لجج" },
{ wrong:"ﶄ", right:"لجج" },
{ wrong:"ﶅ", right:"لخم" },
{ wrong:"ﶆ", right:"لخم" },
{ wrong:"ﶇ", right:"لمح" },
{ wrong:"ﶈ", right:"لمح" },
{ wrong:"ﶉ", right:"محج" },
{ wrong:"ﶊ", right:"محم" },
{ wrong:"ﶋ", right:"محي" },
{ wrong:"ﶌ", right:"مجح" },
{ wrong:"ﶍ", right:"مجم" },
{ wrong:"ﶎ", right:"مخج" },
{ wrong:"ﶏ", right:"مخم" },
{ wrong:"ﶒ", right:"مجخ" },
{ wrong:"ﶓ", right:"همج" },
{ wrong:"ﶔ", right:"همم" },
{ wrong:"ﶕ", right:"نحم" },
{ wrong:"ﶖ", right:"نحى" },
{ wrong:"ﶗ", right:"نجم" },
{ wrong:"ﶘ", right:"نجم" },
{ wrong:"ﶙ", right:"نجى" },
{ wrong:"ﶚ", right:"نمي" },
{ wrong:"ﶛ", right:"نمى" },
{ wrong:"ﶜ", right:"يمم" },
{ wrong:"ﶝ", right:"يمم" },
{ wrong:"ﶞ", right:"بخي" },
{ wrong:"ﶟ", right:"تجي" },
{ wrong:"ﶠ", right:"تجى" },
{ wrong:"ﶡ", right:"تخي" },
{ wrong:"ﶢ", right:"تخى" },
{ wrong:"ﶣ", right:"تمي" },
{ wrong:"ﶤ", right:"تمى" },
{ wrong:"ﶥ", right:"جمي" },
{ wrong:"ﶦ", right:"جحى" },
{ wrong:"ﶧ", right:"جمى" },
{ wrong:"ﶨ", right:"سخى" },
{ wrong:"ﶩ", right:"صحي" },
{ wrong:"ﶪ", right:"شحي" },
{ wrong:"ﶫ", right:"ضحي" },
{ wrong:"ﶬ", right:"لجي" },
{ wrong:"ﶭ", right:"لمي" },
{ wrong:"ﶮ", right:"يحي" },
{ wrong:"ﶯ", right:"يجي" },
{ wrong:"ﶰ", right:"يمي" },
{ wrong:"ﶱ", right:"ممي" },
{ wrong:"ﶲ", right:"قمي" },
{ wrong:"ﶳ", right:"نحي" },
{ wrong:"ﶴ", right:"قمح" },
{ wrong:"ﶵ", right:"لحم" },
{ wrong:"ﶶ", right:"عمي" },
{ wrong:"ﶷ", right:"كمي" },
{ wrong:"ﶸ", right:"نجح" },
{ wrong:"ﶹ", right:"مخي" },
{ wrong:"ﶺ", right:"لجم" },
{ wrong:"ﶻ", right:"كمم" },
{ wrong:"ﶼ", right:"لجم" },
{ wrong:"ﶽ", right:"نجح" },
{ wrong:"ﶾ", right:"جحي" },
{ wrong:"ﶿ", right:"حجي" },
{ wrong:"ﷀ", right:"مجي" },
{ wrong:"ﷁ", right:"فمي" },
{ wrong:"ﷂ", right:"بحي" },
{ wrong:"ﷃ", right:"كمم" },
{ wrong:"ﷄ", right:"عجم" },
{ wrong:"ﷅ", right:"صمم" },
{ wrong:"ﷆ", right:"سخي" },
{ wrong:"ﷇ", right:"نجي" },
{ wrong:"ﷰ", right:"صلے" },
{ wrong:"ﷱ", right:"قلے" },
{ wrong:"ﷲ", right:"الله" },
{ wrong:"ﷳ", right:"اكبر" },
{ wrong:"ﷴ", right:"محمد" },
{ wrong:"ﷵ", right:"صلعم" },
{ wrong:"ﷶ", right:"رسول" },
{ wrong:"ﷷ", right:"عليه" },
{ wrong:"ﷸ", right:"وسلم" },
{ wrong:"ﷹ", right:"صلى" },
{ wrong:"ﷺ", right:"صلى الله عليه وسلم" },
{ wrong:"ﷻ", right:"جل جلاله" },
{ wrong:"﷼", right:"ریال" },


// Presentation forms B
{ wrong:"ﹰ", right:" ً" },
{ wrong:"ﹱ", right:"ـً" },
{ wrong:"ﹲ", right:" ٌ" },
{ wrong:"ﹴ", right:" ٍ" },
{ wrong:"ﹶ", right:" َ" },
{ wrong:"ﹷ", right:"ـَ" },
{ wrong:"ﹸ", right:" ُ" },
{ wrong:"ﹹ", right:"ـُ" },
{ wrong:"ﹺ", right:" ِ" },
{ wrong:"ﹻ", right:"ـِ" },
{ wrong:"ﹼ", right:" ّ" },
{ wrong:"ﹽ", right:"ـّ" },
{ wrong:"ﹾ", right:" ْ" },
{ wrong:"ﹿ", right:"ـْ" },
{ wrong:"ﺀ", right:"ء" },
{ wrong:"ﺁ", right:"آ" },
{ wrong:"ﺂ", right:"آ" },
{ wrong:"ﺃ", right:"أ" },
{ wrong:"ﺄ", right:"أ" },
{ wrong:"ﺅ", right:"ؤ" },
{ wrong:"ﺆ", right:"ؤ" },
{ wrong:"ﺇ", right:"إ" },
{ wrong:"ﺈ", right:"إ" },
{ wrong:"ﺉ", right:"ئ" },
{ wrong:"ﺊ", right:"ئ" },
{ wrong:"ﺋ", right:"ئ" },
{ wrong:"ﺌ", right:"ئ" },
{ wrong:"ﺍ", right:"ا" },
{ wrong:"ﺎ", right:"ا" },
{ wrong:"ﺏ", right:"ب" },
{ wrong:"ﺐ", right:"ب" },
{ wrong:"ﺑ", right:"ب" },
{ wrong:"ﺒ", right:"ب" },
{ wrong:"ﺓ", right:"ة" },
{ wrong:"ﺔ", right:"ة" },
{ wrong:"ﺕ", right:"ت" },
{ wrong:"ﺖ", right:"ت" },
{ wrong:"ﺗ", right:"ت" },
{ wrong:"ﺘ", right:"ت" },
{ wrong:"ﺙ", right:"ث" },
{ wrong:"ﺚ", right:"ث" },
{ wrong:"ﺛ", right:"ث" },
{ wrong:"ﺜ", right:"ث" },
{ wrong:"ﺝ", right:"ج" },
{ wrong:"ﺞ", right:"ج" },
{ wrong:"ﺟ", right:"ج" },
{ wrong:"ﺠ", right:"ج" },
{ wrong:"ﺡ", right:"ح" },
{ wrong:"ﺢ", right:"ح" },
{ wrong:"ﺣ", right:"ح" },
{ wrong:"ﺤ", right:"ح" },
{ wrong:"ﺥ", right:"خ" },
{ wrong:"ﺦ", right:"خ" },
{ wrong:"ﺧ", right:"خ" },
{ wrong:"ﺨ", right:"خ" },
{ wrong:"ﺩ", right:"د" },
{ wrong:"ﺪ", right:"د" },
{ wrong:"ﺫ", right:"ذ" },
{ wrong:"ﺬ", right:"ذ" },
{ wrong:"ﺭ", right:"ر" },
{ wrong:"ﺮ", right:"ر" },
{ wrong:"ﺯ", right:"ز" },
{ wrong:"ﺰ", right:"ز" },
{ wrong:"ﺱ", right:"س" },
{ wrong:"ﺲ", right:"س" },
{ wrong:"ﺳ", right:"س" },
{ wrong:"ﺴ", right:"س" },
{ wrong:"ﺵ", right:"ش" },
{ wrong:"ﺶ", right:"ش" },
{ wrong:"ﺷ", right:"ش" },
{ wrong:"ﺸ", right:"ش" },
{ wrong:"ﺹ", right:"ص" },
{ wrong:"ﺺ", right:"ص" },
{ wrong:"ﺻ", right:"ص" },
{ wrong:"ﺼ", right:"ص" },
{ wrong:"ﺽ", right:"ض" },
{ wrong:"ﺾ", right:"ض" },
{ wrong:"ﺿ", right:"ض" },
{ wrong:"ﻀ", right:"ض" },
{ wrong:"ﻁ", right:"ط" },
{ wrong:"ﻂ", right:"ط" },
{ wrong:"ﻃ", right:"ط" },
{ wrong:"ﻄ", right:"ط" },
{ wrong:"ﻅ", right:"ظ" },
{ wrong:"ﻆ", right:"ظ" },
{ wrong:"ﻇ", right:"ظ" },
{ wrong:"ﻈ", right:"ظ" },
{ wrong:"ﻉ", right:"ع" },
{ wrong:"ﻊ", right:"ع" },
{ wrong:"ﻋ", right:"ع" },
{ wrong:"ﻌ", right:"ع" },
{ wrong:"ﻍ", right:"غ" },
{ wrong:"ﻎ", right:"غ" },
{ wrong:"ﻏ", right:"غ" },
{ wrong:"ﻐ", right:"غ" },
{ wrong:"ﻑ", right:"ف" },
{ wrong:"ﻒ", right:"ف" },
{ wrong:"ﻓ", right:"ف" },
{ wrong:"ﻔ", right:"ف" },
{ wrong:"ﻕ", right:"ق" },
{ wrong:"ﻖ", right:"ق" },
{ wrong:"ﻗ", right:"ق" },
{ wrong:"ﻘ", right:"ق" },
{ wrong:"ﻙ", right:"ك" },
{ wrong:"ﻚ", right:"ك" },
{ wrong:"ﻛ", right:"ك" },
{ wrong:"ﻜ", right:"ك" },
{ wrong:"ﻝ", right:"ل" },
{ wrong:"ﻞ", right:"ل" },
{ wrong:"ﻟ", right:"ل" },
{ wrong:"ﻠ", right:"ل" },
{ wrong:"ﻡ", right:"م" },
{ wrong:"ﻢ", right:"م" },
{ wrong:"ﻣ", right:"م" },
{ wrong:"ﻤ", right:"م" },
{ wrong:"ﻥ", right:"ن" },
{ wrong:"ﻦ", right:"ن" },
{ wrong:"ﻧ", right:"ن" },
{ wrong:"ﻨ", right:"ن" },
{ wrong:"ﻩ", right:"ه" },
{ wrong:"ﻪ", right:"ه" },
{ wrong:"ﻫ", right:"ه" },
{ wrong:"ﻬ", right:"ه" },
{ wrong:"ﻭ", right:"و" },
{ wrong:"ﻮ", right:"و" },
{ wrong:"ﻯ", right:"ى" },
{ wrong:"ﻰ", right:"ى" },
{ wrong:"ﻱ", right:"ي" },
{ wrong:"ﻲ", right:"ي" },
{ wrong:"ﻳ", right:"ي" },
{ wrong:"ﻴ", right:"ي" },
{ wrong:"ﻵ", right:"لآ" },
{ wrong:"ﻶ", right:"لآ" },
{ wrong:"ﻷ", right:"لأ" },
{ wrong:"ﻸ", right:"لأ" },
{ wrong:"ﻹ", right:"لإ" },
{ wrong:"ﻺ", right:"لإ" },
{ wrong:"ﻻ", right:"لا" },
{ wrong:"ﻼ", right:"لا" },
]




function makelist (str) {
    changed = []
    var chars = [...str]
    for (var i=0;i<chars.length;i++) {
        if (chars[i] !== chars[i].normalize('NFKC')) changed.push(chars[i])
        }
    if (changed.length > 0) {
        const uniqueSet = new Set(changed)
        var uniqueArray = [...uniqueSet]
        out = ''
        for (c=0;c<uniqueArray.length;c++) {
            out += `{ wrong:"${ uniqueArray[c] }", right:"${ uniqueArray[c].normalize('NFKC') }" },\n`
            }
        }
    console.log(out)
    }



_characterSet = 
"ئا ا ئە ە ب پ ت ج چ خ د ر ز ژ س ش غ ف ق ك گ ڭ ل م ن ھ ئو و ئۇ ۇ ئۆ ۆ ئۈ ۈ ۋ ئې ې ئى ىي ي ٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩ ؟ ، ؛"




var _h = {
'627': ['661'],
'622': ['661'],
'623': ['661', '654'],
'625': ['661', '655'],
'671': ['661'],
'6F1': ['671', '625', '623', '622', '627'],
'639': ['60F'],
'63A': ['60F'],
'60F': ['639', '63A'],
'657': ['64F'],
'620': ['60E'],
'60E': ['602'],
'66B': ['631'],
'631': ['66B'],
'654': ['626', '624', '623'],
'655': ['625'],
'626': ['654'],
'624': ['654'],

end: {}
}


var keyboarddef = [
"§ ذ ّ|1 ١|2 ٢|3 ٣|4 ٤|5 ٥|6 ٦|7 ٧|8 ٨|9 ٩|0 ٠|- «|= »",
"q ض َ ‘|w ص ً ’|e ث ُ “|r ق ٌ ”|t ف لإ ڤ|y غ إ|u ع ‘ ە|i ه ÷|o خ ×|p ح ؛|[ ج < چ|] د >",
"a ش ِ |s س ٍ ے|d ي ]\ ی|f ب [\ پ|g ل لأ ٓ|h ا أ ٰ|j ت ـ ٹ|k ن ، ں|l م /|; ك : گ|' ط \" …|\\",
"` ٫ ٬|z ئ ~|x ء ْ|c ؤ } ڈ|v ر { ڑ|b لا لآ ژ|n ى آ|m ة ’|, و|.  ز|/ ظ ؟"
]



function setLocalButtons () {
	// overrides the function that hides the makeEg and charLink buttons
	
	}


var rightOnly = new Set(['ا', 'آ', 'أ', 'إ', 'ٱ', 'ة', 'و', 'ؤ', 'ر', 'ز', 'د', 'ذ'])

var bothJoin = new Set(['ل', 'ك', 'ع', 'غ', 'ح', 'خ', 'ج', 'ف', 'ق', 'ط', 'ظ', 'ه', 'ي', 'ئ', 'ى', 'م', 'ب', 'ت', 'ث', 'ن', 'ص', 'ض', 'س', 'ش'])



function convertFromNFKC (str) {
    // replaces Arabic Presentation form code points with standard code points
    
    changed = []
    var chars = [...str]
    for (var i=0;i<chars.length;i++) {
        if (chars[i] !== chars[i].normalize('NFKC')) changed.push(chars[i])
        }
    if (changed.length > 0) {
        const uniqueSet = new Set(changed)
        var uniqueArray = [...uniqueSet]
        alert(changed.length+' characters were converted.\nHere is a list of unique codepoints changed: '+uniqueArray.join(' '))
        }
    return str.normalize('NFKC')
    }








var ipaCharacterMap = `
a ɑː ا ɑ ة a ى ɑt ة ʔɑː آ
A a َ an ً
b b ب
d d د dˤ ض ðˤ ظ ð ذ
f f ف f ڢ
h h ہ ħ ح
i iː ي
I i ِ in ٍ
j j ي
k k ك
l l ل
m m م
n n ن
q q ق q ڧ
r r ر
s s س sˤ ص ʃ ش
t t ت tˤ ط
u uː و
U u ُ un ٌ
w w و
x x خ
y ɣ غ
z z ز ʒ ج
@ θ ث
{ ʕ ع
} ʔ ء
[ ° ْ ᵚ ّ
§ 0 ٠ 1 ١ 2 ٢ 3 ٣ 4 ٤ 5 ٥ 6 ٦ 7 ٧ 8 ٨ 9 ٩
; ; ؛
_ _ ـ
, , ،
. . ۔
? ? ؟
% % ٪
`


