function localtranscribe (direction, str) {
	
	if (direction == 'transliterate') { return transliterate(str) }
	if (direction == 'toLatin') { return toLatin(str) }
	}
		



function transliterate (str) {
console.log('transliterate')
str = ' '+str

var strArray = [...str]
var exclusions = new Set(['(',')','[',']','.',' '])

for (i=0;i<strArray.length;i++) {
	if (exclusions.has(strArray[i])) continue
	if (! autoTranslitArray[strArray[i]]) continue
	re = new RegExp(strArray[i],'g')
	str = str.replace(re, autoTranslitArray[strArray[i]])
	}


return str.trim()
}




function toLatin (str) {
	
str = str.replace(/ꚧ꛰ꚢ/g, "vu")
str = str.replace(/ꚶꛉ꛰/g, "ʃü")
str = str.replace(/ꚷꚧ꛰/g, "sü")
str = str.replace(/ꛑꚧ꛰/g, "rü")
str = str.replace(/ꛫꚧ꛰/g, "tu")
str = str.replace(/ꚠ꛰/g, "aʔ")
str = str.replace(/ꚡ꛰/g, "kaʔ")
str = str.replace(/ꚢ꛰/g, "wu")
str = str.replace(/ꚣ꛰/g, "kuʔ")
str = str.replace(/ꚤ꛰/g, "eʔ")
str = str.replace(/ꚥ꛰/g, "rɛn")
str = str.replace(/ꚦꚧ/g, "tɔ")
str = str.replace(/ꚦ꛰/g, "tɔʔ")
str = str.replace(/ꚧ꛰/g, "ɔʔ")
str = str.replace(/ꚧ꛱/g, "ə")
str = str.replace(/ꚨ꛰/g, "nye")
str = str.replace(/ꚩ꛰/g, "iʔ")
str = str.replace(/ꚪ꛰/g, "laʔ")
str = str.replace(/ꚫ꛰/g, "paʔ")
str = str.replace(/ꚬ꛰/g, "riʔ")
str = str.replace(/ꚭ꛰/g, "z")
str = str.replace(/ꚮ꛰/g, "leʔ")
str = str.replace(/ꚯ꛰/g, "[meʔ{]")
str = str.replace(/ꚰ꛰/g, "taʔ")
str = str.replace(/ꚱꚤ/g, "de")
str = str.replace(/ꚱꚧ/g, "do")
str = str.replace(/ꚱꚩ/g, "di")
str = str.replace(/ꚱ꛰/g, "ndaʔ")
str = str.replace(/ꚱ꛱/g, "nd")
str = str.replace(/ꚲ꛰/g, "yem")
str = str.replace(/ꚳ꛰/g, "n")
str = str.replace(/ꚴ꛰/g, "suʔ")
str = str.replace(/ꚵ꛰/g, "muʔ")
str = str.replace(/ꚶꚩ/g, "ji")
str = str.replace(/ꚶ꛰/g, "ʃiʔ")
str = str.replace(/ꚶ꛱/g, "ʃ")
str = str.replace(/ꚷꚤ/g, "se")
str = str.replace(/ꚷ꛰/g, "siʔ")
str = str.replace(/ꚷ꛱/g, "s")
str = str.replace(/ꚸ꛰/g, "yɯx")
str = str.replace(/ꚹ꛰/g, "sɯʔ")
str = str.replace(/ꚺ꛰/g, "kyeʔ")
str = str.replace(/ꚻ꛰/g, "keʔ")
str = str.replace(/ꚼ꛰/g, "ŋuə")
str = str.replace(/ꚽ꛰/g, "nuʔ")
str = str.replace(/ꚾ꛰/g, "yuən")
str = str.replace(/ꚾ꛱/g, "y")
str = str.replace(/ꚿꚢ/g, "jo")
str = str.replace(/ꚿ꛰/g, "yɔʔ")
str = str.replace(/ꛀ꛰/g, "ʃuʔ")
str = str.replace(/ꛁ꛰/g, "yun")
str = str.replace(/ꛂ꛰/g, "yaʔ")
str = str.replace(/ꛃꚠ/g, "ja")
str = str.replace(/ꛃ꛰/g, "ʃaʔ")
str = str.replace(/ꛄ꛰/g, "ɣɯ")
str = str.replace(/ꛅꚧ/g, "pɔ")
str = str.replace(/ꛅ꛰/g, "pɯʔ")
str = str.replace(/ꛆ꛰/g, "nʒeʔ")
str = str.replace(/ꛇ꛰/g, "teʔ")
str = str.replace(/ꛈ꛰/g, "püʔ")
str = str.replace(/ꛉ꛰/g, "üʔ")
str = str.replace(/ꛊ꛰/g, "peʔ")
str = str.replace(/ꛋ꛰/g, "feʔ")
str = str.replace(/ꛌ꛰/g, "ruʔ")
str = str.replace(/ꛍ꛰/g, "luʔ")
str = str.replace(/ꛎ꛰/g, "miʔ")
str = str.replace(/ꛏ꛰/g, "nɛn")
str = str.replace(/ꛐ꛰/g, "rɯʔ")
str = str.replace(/ꛑꚠ/g, "ra")
str = str.replace(/ꛑ꛰/g, "rɔ")
str = str.replace(/ꛒ꛰/g, "kɛn")
str = str.replace(/ꛓ꛰/g, "ŋuət")
str = str.replace(/ꛔꚤ/g, "gi")
str = str.replace(/ꛔꚧ/g, "guei")
str = str.replace(/ꛔ꛰/g, "ŋgaʔ")
str = str.replace(/ꛔ꛱/g, "ŋg")
str = str.replace(/ꛕ꛰/g, "ŋaʔ")
str = str.replace(/ꛖ꛰/g, "ʃɔʔ")
str = str.replace(/ꛖ꛱/g, "ʃ")
str = str.replace(/ꛗꚢ/g, "bo")
str = str.replace(/ꛗꚧ/g, "bɔ")
str = str.replace(/ꛗ꛰/g, "puʔ")
str = str.replace(/ꛘꚧ/g, "fɔ")
str = str.replace(/ꛘ꛰/g, "fuʔ")
str = str.replace(/ꛘ꛱/g, "f")
str = str.replace(/ꛙ꛰/g, "mvɔp")
str = str.replace(/ꛚ꛰/g, "waʔ")
str = str.replace(/ꛛ꛰/g, "naʔ")
str = str.replace(/ꛛ꛱/g, "n")
str = str.replace(/ꛜ꛰/g, "liʔ")
str = str.replace(/ꛜ꛱/g, "l")
str = str.replace(/ꛝ꛰/g, "pin")
str = str.replace(/ꛞ꛰/g, "lɔʔ")
str = str.replace(/ꛟꚧ/g, "ko")
str = str.replace(/ꛟ꛰/g, "kɔʔ")
str = str.replace(/ꛟ꛱/g, "k")
str = str.replace(/ꛠ꛰/g, "pɛn")
str = str.replace(/ꛡ꛰/g, "rɛn")
str = str.replace(/ꛢ꛰/g, "mɛn")
str = str.replace(/ꛣ꛰/g, "maʔ")
str = str.replace(/ꛤ꛰/g, "tɯ")
str = str.replace(/ꛤ꛱/g, "t")
str = str.replace(/ꛥ꛰/g, "kiʔ")
str = str.replace(/ꛦ꛰/g, "mɔn")
str = str.replace(/ꛦ꛱/g, "m")
str = str.replace(/ꛧ꛰/g, "mbaʔ")
str = str.replace(/ꛨ꛰/g, "tɛt")
str = str.replace(/ꛩ꛰/g, "ŋma")
str = str.replace(/ꛪ꛰/g, "tɛn")
str = str.replace(/ꛫꚢ/g, "dɔ")
str = str.replace(/ꛫ꛰/g, "tuʔ")
str = str.replace(/ꛬ꛰/g, "saʔ")
str = str.replace(/ꛭ꛰/g, "faʔ")
str = str.replace(/ꛮꚤ/g, "ve")
str = str.replace(/ꛮꚩ/g, "vi")
str = str.replace(/ꛮ꛰/g, "fü")
str = str.replace(/ꛯ꛰/g, "ŋgɔm")
str = str.replace(/ꚠ/g, "a")
str = str.replace(/ꚡ/g, "ka")
str = str.replace(/ꚢ/g, "u")
str = str.replace(/ꚣ/g, "ku")
str = str.replace(/ꚤ/g, "e")
str = str.replace(/ꚥ/g, "re")
str = str.replace(/ꚦ/g, "te")
str = str.replace(/ꚧ/g, "ɔ")
str = str.replace(/ꚨ/g, "nyi")
str = str.replace(/ꚩ/g, "i")
str = str.replace(/ꚪ/g, "la")
str = str.replace(/ꚫ/g, "pa")
str = str.replace(/ꚬ/g, "rii")
str = str.replace(/ꚭ/g, "rie")
str = str.replace(/ꚮ/g, "lee")
str = str.replace(/ꚯ/g, "mee")
str = str.replace(/ꚰ/g, "taa")
str = str.replace(/ꚱ/g, "nda")
str = str.replace(/ꚲ/g, "njem")
str = str.replace(/ꚳ/g, "m")
str = str.replace(/ꚴ/g, "suu")
str = str.replace(/ꚵ/g, "mu")
str = str.replace(/ꚶ/g, "ʃii")
str = str.replace(/ꚷ/g, "si")
str = str.replace(/ꚸ/g, "ʃɯx")
str = str.replace(/ꚹ/g, "sɯx")
str = str.replace(/ꚺ/g, "kye")
str = str.replace(/ꚻ/g, "kɛt")
str = str.replace(/ꚼ/g, "nuə")
str = str.replace(/ꚽ/g, "nu")
str = str.replace(/ꚾ/g, "nʒuə")
str = str.replace(/ꚿ/g, "yɔʔ")
str = str.replace(/ꛀ/g, "ʃu")
str = str.replace(/ꛁ/g, "yu")
str = str.replace(/ꛂ/g, "ya")
str = str.replace(/ꛃ/g, "nʃa")
str = str.replace(/ꛄ/g, "kɯx")
str = str.replace(/ꛅ/g, "pɯx")
str = str.replace(/ꛆ/g, "nʒe")
str = str.replace(/ꛇ/g, "nte")
str = str.replace(/ꛈ/g, "py")
str = str.replace(/ꛉ/g, "wü")
str = str.replace(/ꛊ/g, "pe")
str = str.replace(/ꛋ/g, "fe")
str = str.replace(/ꛌ/g, "ru")
str = str.replace(/ꛍ/g, "lu")
str = str.replace(/ꛎ/g, "mi")
str = str.replace(/ꛏ/g, "ni")
str = str.replace(/ꛐ/g, "rɯx")
str = str.replace(/ꛑ/g, "rə")
str = str.replace(/ꛒ/g, "kɛn")
str = str.replace(/ꛓ/g, "ŋkwən")
str = str.replace(/ꛔ/g, "ŋga")
str = str.replace(/ꛕ/g, "ŋa")
str = str.replace(/ꛖ/g, "ʃɔ")
str = str.replace(/ꛗ/g, "puə")
str = str.replace(/ꛘ/g, "fu")
str = str.replace(/ꛙ/g, "fɔm")
str = str.replace(/ꛚ/g, "wa")
str = str.replace(/ꛛ/g, "nan")
str = str.replace(/ꛜ/g, "li")
str = str.replace(/ꛝ/g, "pi")
str = str.replace(/ꛞ/g, "lɔʔ")
str = str.replace(/ꛟ/g, "kɔ")
str = str.replace(/ꛠ/g, "mbɛn")
str = str.replace(/ꛡ/g, "rɛn")
str = str.replace(/ꛢ/g, "mɛn")
str = str.replace(/ꛣ/g, "ma")
str = str.replace(/ꛤ/g, "ti")
str = str.replace(/ꛥ/g, "ki")
str = str.replace(/ꛦ/g, "mɔ")
str = str.replace(/ꛧ/g, "mbaa")
str = str.replace(/ꛨ/g, "tɛt")
str = str.replace(/ꛩ/g, "kpa")
str = str.replace(/ꛪ/g, "tɛn")
str = str.replace(/ꛫ/g, "ntuu")
str = str.replace(/ꛬ/g, "sa")
str = str.replace(/ꛭ/g, "faa")
str = str.replace(/ꛮ/g, "vü")
str = str.replace(/ꛯ/g, "ɣɔm")

str = str.replace(/ˀ/g, "ʔ")
str = str.replace(/ⁱ/g, "i")
str = str.replace(/ʲ/g, "y")
str = str.replace(/ʸ/g, "ü")
str = str.replace(/ᵚ/g, "ɯ")
str = str.replace(/ˣ/g, "x")
str = str.replace(/ᵘ/g, "u")
str = str.replace(/ᵊ/g, "ə")
str = str.replace(/ᵉ/g, "e")
str = str.replace(/ᵓ/g, "ɔ")
str = str.replace(/ᵃ/g, "a")
str = str.replace(/ᵒ/g, "o")
str = str.replace(/ᵋ/g, "ɛ")
str = str.replace(/ᵖ/g, "p")
str = str.replace(/ᵐ/g, "m")
str = str.replace(/ᵇ/g, "b")
str = str.replace(/ᵛ/g, "v")
str = str.replace(/ᵗ/g, "t")
str = str.replace(/ᵈ/g, "d")
str = str.replace(/ᶾ/g, "ʒ")
str = str.replace(/ᵏ/g, "k")
str = str.replace(/ʷ/g, "w")
str = str.replace(/̃/g, "n")

// uppercase letter following NJAEMLI and remove the latter from the string
strArray = [...str]
newArray = []
var NJAEMLIfound = false
for (let i=0;i<strArray.length;i++) {
	if (strArray[i] === '꛲') NJAEMLIfound = true
	else if (NJAEMLIfound) {
		newArray.push(strArray[i].toUpperCase())
		NJAEMLIfound = false
		}
	else newArray.push(strArray[i])
	}

str = newArray.join('')

return str.trim()
}





function reverse (str) { 
    
str += '  '

str = str.replace(/kpe/g, "ꔉ")
str = str.replace(/mgbe/g, "ꔊ")
str = str.replace(/gbe/g, "ꔋ")
str = str.replace(/mɓe/g, "ꔈ")
str = str.replace(/nɗe/g, "ꔕ")
str = str.replace(/nʤe/g, "ꔜ")
str = str.replace(/ŋge/g, "ꔟ")
str = str.replace(/ẹ̃/g, "ꔁ")
str = str.replace(/ẹ/g, "ꔀ")
str = str.replace(/he/g, "ꔂ")
str = str.replace(/wẽ/g, "ꔄ")
str = str.replace(/we/g, "ꔃ")
str = str.replace(/pe/g, "ꔅ")
str = str.replace(/be/g, "ꔆ")
str = str.replace(/ɓe/g, "ꔇ")
str = str.replace(/fe/g, "ꔌ")
str = str.replace(/ve/g, "ꔍ")
str = str.replace(/te/g, "ꔎ")
str = str.replace(/θe/g, "ꔏ")
str = str.replace(/de/g, "ꔐ")
str = str.replace(/ðe/g, "ꔑ")
str = str.replace(/le/g, "ꔒ")
str = str.replace(/re/g, "ꔓ")
str = str.replace(/ɗe/g, "ꔔ")
str = str.replace(/se/g, "ꔖ")
str = str.replace(/ʃe/g, "ꔗ")
str = str.replace(/ze/g, "ꔘ")
str = str.replace(/ʒe/g, "ꔙ")
str = str.replace(/ʧe/g, "ꔚ")
str = str.replace(/ʤe/g, "ꔛ")
str = str.replace(/je/g, "ꔝ")
str = str.replace(/ke/g, "ꔞ")
str = str.replace(/ge/g, "ꔠ")
str = str.replace(/mẽ/g, "ꔡ")
str = str.replace(/nẽ/g, "ꔢ")
str = str.replace(/ɲẽ/g, "ꔣ")

str = str.replace(/mɓi/g, "ꔭ")
str = str.replace(/kpi/g, "ꔮ")
str = str.replace(/mgbi/g, "ꔯ")
str = str.replace(/gbi/g, "ꔰ")
str = str.replace(/nɗi/g, "ꔺ")
str = str.replace(/nʤi/g, "ꕁ")
str = str.replace(/ŋgi/g, "ꕄ")
str = str.replace(/ị̃/g, "ꔥ")
str = str.replace(/ị/g, "ꔤ")
str = str.replace(/hĩ/g, "ꔧ")
str = str.replace(/hi/g, "ꔦ")
str = str.replace(/wĩ/g, "ꔩ")
str = str.replace(/wi/g, "ꔨ")
str = str.replace(/pi/g, "ꔪ")
str = str.replace(/bi/g, "ꔫ")
str = str.replace(/ɓi/g, "ꔬ")
str = str.replace(/fi/g, "ꔱ")
str = str.replace(/vi/g, "ꔲ")
str = str.replace(/ti/g, "ꔳ")
str = str.replace(/θi/g, "ꔴ")
str = str.replace(/di/g, "ꔵ")
str = str.replace(/ði/g, "ꔶ")
str = str.replace(/li/g, "ꔷ")
str = str.replace(/ri/g, "ꔸ")
str = str.replace(/ɗi/g, "ꔹ")
str = str.replace(/si/g, "ꔻ")
str = str.replace(/ʃi/g, "ꔼ")
str = str.replace(/zi/g, "ꔽ")
str = str.replace(/ʒi/g, "ꔾ")
str = str.replace(/ʧi/g, "ꔿ")
str = str.replace(/ʤi/g, "ꕀ")
str = str.replace(/ji/g, "ꕂ")
str = str.replace(/ki/g, "ꕃ")
str = str.replace(/gi/g, "ꕅ")
str = str.replace(/mĩ/g, "ꕆ")
str = str.replace(/nĩ/g, "ꕇ")
str = str.replace(/ɲĩ/g, "ꕈ")

str = str.replace(/mɓa/g, "ꕓ")
str = str.replace(/kpã/g, "ꕕ")
str = str.replace(/kpa/g, "ꕔ")
str = str.replace(/mgba/g, "ꕖ")
str = str.replace(/gba/g, "ꕗ")
str = str.replace(/nɗa/g, "ꕡ")
str = str.replace(/nʤa/g, "ꕨ")
str = str.replace(/ŋga/g, "ꕬ")
str = str.replace(/ạ̃/g, "ꕊ")
str = str.replace(/ạ/g, "ꕉ")
str = str.replace(/ŋã/g, "ꕋ")
str = str.replace(/hã/g, "ꕍ")
str = str.replace(/ha/g, "ꕌ")
str = str.replace(/wã/g, "ꕏ")
str = str.replace(/wa/g, "ꕎ")
str = str.replace(/pa/g, "ꕐ")
str = str.replace(/ba/g, "ꕑ")
str = str.replace(/ɓa/g, "ꕒ")
str = str.replace(/fa/g, "ꕘ")
str = str.replace(/va/g, "ꕙ")
str = str.replace(/ta/g, "ꕚ")
str = str.replace(/θa/g, "ꕛ")
str = str.replace(/da/g, "ꕜ")
str = str.replace(/ða/g, "ꕝ")
str = str.replace(/la/g, "ꕞ")
str = str.replace(/ra/g, "ꕟ")
str = str.replace(/ɗa/g, "ꕠ")
str = str.replace(/sa/g, "ꕢ")
str = str.replace(/ʃa/g, "ꕣ")
str = str.replace(/za/g, "ꕤ")
str = str.replace(/ʒa/g, "ꕥ")
str = str.replace(/ʧa/g, "ꕦ")
str = str.replace(/ʤa/g, "ꕧ")
str = str.replace(/ja/g, "ꕩ")
str = str.replace(/kã/g, "ꕫ")
str = str.replace(/ka/g, "ꕪ")
str = str.replace(/ga/g, "ꕭ")
str = str.replace(/mã/g, "ꕮ")
str = str.replace(/nã/g, "ꕯ")
str = str.replace(/ɲã/g, "ꕰ")

str = str.replace(/mɓo/g, "ꕹ")
str = str.replace(/kpo/g, "ꕺ")
str = str.replace(/mgbo/g, "ꕻ")
str = str.replace(/gbo/g, "ꕼ")
str = str.replace(/nɗo/g, "ꖆ")
str = str.replace(/nʤo/g, "ꖍ")
str = str.replace(/ŋgo/g, "ꖐ")
str = str.replace(/ọ̃/g, "ꕲ")
str = str.replace(/ọ/g, "ꕱ")
str = str.replace(/ho/g, "ꕳ")
str = str.replace(/wõ/g, "ꕵ")
str = str.replace(/wo/g, "ꕴ")
str = str.replace(/po/g, "ꕶ")
str = str.replace(/bo/g, "ꕷ")
str = str.replace(/ɓo/g, "ꕸ")
str = str.replace(/fo/g, "ꕽ")
str = str.replace(/vo/g, "ꕾ")
str = str.replace(/to/g, "ꕿ")
str = str.replace(/θo/g, "ꖀ")
str = str.replace(/do/g, "ꖁ")
str = str.replace(/ðo/g, "ꖂ")
str = str.replace(/lo/g, "ꖃ")
str = str.replace(/ro/g, "ꖄ")
str = str.replace(/ɗo/g, "ꖅ")
str = str.replace(/so/g, "ꖇ")
str = str.replace(/ʃo/g, "ꖈ")
str = str.replace(/zo/g, "ꖉ")
str = str.replace(/ʒo/g, "ꖊ")
str = str.replace(/ʧo/g, "ꖋ")
str = str.replace(/ʤo/g, "ꖌ")
str = str.replace(/jo/g, "ꖎ")
str = str.replace(/ko/g, "ꖏ")
str = str.replace(/go/g, "ꖑ")
str = str.replace(/mõ/g, "ꖒ")
str = str.replace(/nõ/g, "ꖓ")
str = str.replace(/ɲõ/g, "ꖔ")

str = str.replace(/mɓu/g, "ꖞ")
str = str.replace(/kpu/g, "ꖟ")
str = str.replace(/mgbu/g, "ꖠ")
str = str.replace(/gbu/g, "ꖡ")
str = str.replace(/nɗu/g, "ꖫ")
str = str.replace(/nʤu/g, "ꖲ")
str = str.replace(/ŋgu/g, "ꖵ")
str = str.replace(/ụ̃/g, "ꖖ")
str = str.replace(/ụ/g, "ꖕ")
str = str.replace(/hũ/g, "ꖘ")
str = str.replace(/hu/g, "ꖗ")
str = str.replace(/wũ/g, "ꖚ")
str = str.replace(/wu/g, "ꖙ")
str = str.replace(/pu/g, "ꖛ")
str = str.replace(/bu/g, "ꖜ")
str = str.replace(/ɓu/g, "ꖝ")
str = str.replace(/fu/g, "ꖢ")
str = str.replace(/vu/g, "ꖣ")
str = str.replace(/tu/g, "ꖤ")
str = str.replace(/θu/g, "ꖥ")
str = str.replace(/du/g, "ꖦ")
str = str.replace(/ðu/g, "ꖧ")
str = str.replace(/lu/g, "ꖨ")
str = str.replace(/ru/g, "ꖩ")
str = str.replace(/ɗu/g, "ꖪ")
str = str.replace(/su/g, "ꖬ")
str = str.replace(/ʃu/g, "ꖭ")
str = str.replace(/zu/g, "ꖮ")
str = str.replace(/ʒu/g, "ꖯ")
str = str.replace(/ʧu/g, "ꖰ")
str = str.replace(/ʤu/g, "ꖱ")
str = str.replace(/ju/g, "ꖳ")
str = str.replace(/ku/g, "ꖴ")
str = str.replace(/gu/g, "ꖶ")
str = str.replace(/mũ/g, "ꖷ")
str = str.replace(/nũ/g, "ꖸ")
str = str.replace(/ɲũ/g, "ꖹ")

str = str.replace(/mɓɔ/g, "ꗄ")
str = str.replace(/kpɔ/g, "ꗅ")
str = str.replace(/mgbɔ/g, "ꗆ")
str = str.replace(/gbɔ̃/g, "ꗈ")
str = str.replace(/gbɔ/g, "ꗇ")
str = str.replace(/nɗɔ/g, "ꗒ")
str = str.replace(/nʤɔ/g, "ꗙ")
str = str.replace(/ŋgɔ/g, "ꗜ")
str = str.replace(/ɔ̣̃/g, "ꖻ")
str = str.replace(/ɔ̣/g, "ꖺ")
str = str.replace(/ŋɔ/g, "ꖼ")
str = str.replace(/hɔ̃/g, "ꖾ")
str = str.replace(/hɔ/g, "ꖽ")
str = str.replace(/wɔ̃/g, "ꗀ")
str = str.replace(/wɔ/g, "ꖿ")
str = str.replace(/pɔ/g, "ꗁ")
str = str.replace(/bɔ/g, "ꗂ")
str = str.replace(/ɓɔ/g, "ꗃ")
str = str.replace(/fɔ/g, "ꗉ")
str = str.replace(/vɔ/g, "ꗊ")
str = str.replace(/tɔ/g, "ꗋ")
str = str.replace(/θɔ/g, "ꗌ")
str = str.replace(/dɔ/g, "ꗍ")
str = str.replace(/ðɔ/g, "ꗎ")
str = str.replace(/lɔ/g, "ꗏ")
str = str.replace(/rɔ/g, "ꗐ")
str = str.replace(/ɗɔ/g, "ꗑ")
str = str.replace(/sɔ/g, "ꗓ")
str = str.replace(/ʃɔ/g, "ꗔ")
str = str.replace(/zɔ/g, "ꗕ")
str = str.replace(/ʒɔ/g, "ꗖ")
str = str.replace(/ʧɔ/g, "ꗗ")
str = str.replace(/ʤɔ/g, "ꗘ")
str = str.replace(/jɔ/g, "ꗚ")
str = str.replace(/kɔ/g, "ꗛ")
str = str.replace(/gɔ/g, "ꗝ")
str = str.replace(/mɔ̃/g, "ꗞ")
str = str.replace(/nɔ̃/g, "ꗟ")
str = str.replace(/ɲɔ̃/g, "ꗠ")

str = str.replace(/mɓɛ/g, "ꗫ")
str = str.replace(/kpɛ̃/g, "ꗭ")
str = str.replace(/kpɛ/g, "ꗬ")
str = str.replace(/mgbɛ/g, "ꗮ")
str = str.replace(/gbɛ̃/g, "ꗰ")
str = str.replace(/gbɛ/g, "ꗯ")
str = str.replace(/nɗɛ/g, "ꗺ")
str = str.replace(/nʤɛ/g, "ꘁ")
str = str.replace(/ŋgɛ̃/g, "ꘅ")
str = str.replace(/ŋgɛ/g, "ꘄ")
str = str.replace(/ɛ̣̃/g, "ꗢ")
str = str.replace(/ɛ̣/g, "ꗡ")
str = str.replace(/ŋɛ̃/g, "ꗣ")
str = str.replace(/hɛ̃/g, "ꗥ")
str = str.replace(/hɛ/g, "ꗤ")
str = str.replace(/wɛ̃/g, "ꗧ")
str = str.replace(/wɛ/g, "ꗦ")
str = str.replace(/pɛ/g, "ꗨ")
str = str.replace(/bɛ/g, "ꗩ")
str = str.replace(/ɓɛ/g, "ꗪ")
str = str.replace(/fɛ/g, "ꗱ")
str = str.replace(/vɛ/g, "ꗲ")
str = str.replace(/tɛ/g, "ꗳ")
str = str.replace(/θɛ/g, "ꗴ")
str = str.replace(/dɛ/g, "ꗵ")
str = str.replace(/ðɛ/g, "ꗶ")
str = str.replace(/lɛ/g, "ꗷ")
str = str.replace(/rɛ/g, "ꗸ")
str = str.replace(/ɗɛ/g, "ꗹ")
str = str.replace(/sɛ/g, "ꗻ")
str = str.replace(/ʃɛ/g, "ꗼ")
str = str.replace(/zɛ/g, "ꗽ")
str = str.replace(/ʒɛ/g, "ꗾ")
str = str.replace(/ʧɛ/g, "ꗿ")
str = str.replace(/ʤɛ/g, "ꘀ")
str = str.replace(/jɛ/g, "ꘂ")
str = str.replace(/kɛ/g, "ꘃ")
str = str.replace(/gɛ̃/g, "ꘇ")
str = str.replace(/gɛ/g, "ꘆ")
str = str.replace(/mɛ̃/g, "ꘈ")
str = str.replace(/nɛ̃/g, "ꘉ")
str = str.replace(/ɲɛ̃/g, "ꘊ")

// syllable finals
str = str.replace(/ŋ̽/g, "ꘋ")
str = str.replace(/–/g, "ꘌ")

// logograms
str = str.replace(/FAA/g, "ꘘ")
str = str.replace(/FENG/g, "ꘓ")

str = str.replace(/FEŊ/g, "ꘓ")
str = str.replace(/KEŊ/g, "ꘔ")
str = str.replace(/TIŊ/g, "ꘕ")
str = str.replace(/NII/g, "ꘖ")
str = str.replace(/BAŊ/g, "ꘗ")
str = str.replace(/TAA/g, "ꘙ")
str = str.replace(/DAŊ/g, "ꘚ")
str = str.replace(/DOŊ/g, "ꘛ")
str = str.replace(/KUŊ/g, "ꘜ")
str = str.replace(/TƆŊ/g, "ꘝ")
str = str.replace(/DƆƆ̣/g, "ꘞ")
str = str.replace(/JƆŊ/g, "ꘟ")


// punctuation
str = str.replace(/,/g, "꘍")
str = str.replace(/!/g, "꘎꘎")
str = str.replace(/\./g, "꘎")
str = str.replace(/\?/g, "꘏")

// numbers
str = str.replace(/0/g, "꘠")
str = str.replace(/1/g, "꘡")
str = str.replace(/2/g, "꘢")
str = str.replace(/3/g, "꘣")
str = str.replace(/4/g, "꘤")
str = str.replace(/5/g, "꘥")
str = str.replace(/6/g, "꘦")
str = str.replace(/7/g, "꘧")
str = str.replace(/8/g, "꘨")
str = str.replace(/9/g, "꘩")



return str.trim()
}





