function localtranscribe (direction, str) {
	
	if (direction == 'transliterate') { return transliterate(str) }
	if (direction == 'toIPA') { return transcribetoIPA(str) }
	if (direction == 'toLatin') { return transcribetoLatin(str) }
	if (direction == 'reverse') { return reverse(str) }
	}
		



function transliterate (str) {

str = ' '+str

var strArray = [...str]
var exclusions = new Set(['(',')','[',']','.',' '])

for (i=0;i<strArray.length;i++) {
	if (exclusions.has(strArray[i])) continue
	if (! autoTranslitArray[strArray[i]]) continue
	re = new RegExp(strArray[i],'g')
	str = str.replace(re, autoTranslitArray[strArray[i]])
	}


return str.trim()
}




function transcribetoIPA (str) {
	str = transliterate(str)
	
	str = str.replace(/kᶣ/g, "HK")
	str = str.replace(/ⁱ̠/g, "iː")
	str = str.replace(/ᵒ̱/g, "oː")
	str = str.replace(/ᵃ̱/g, "aː")
	str = str.replace(/ⁱ/g, "i")
	str = str.replace(/ᵃ/g, "a")
	str = str.replace(/ᵒ/g, "o")
	str = str.replace(/ʷ/g, "w")
	str = str.replace(/ᵉ/g, "eː")
	str = str.replace(/e/g, "eː")
	str = str.replace(/\u202F/g, "-")
	str = str.replace(/\u00A0/g, "-")

	return str.trim().toLowerCase()
	}




function transcribetoLatin (str) {
	str = transliterate(str)
	
	str = str.replace(/kᶣ/g, "HK")
	str = str.replace(/ⁱ̠/g, "ī")
	str = str.replace(/ᵒ̱/g, "ō")
	str = str.replace(/ᵃ̱/g, "ā")
	str = str.replace(/ⁱ/g, "i")
	str = str.replace(/ᵃ/g, "a")
	str = str.replace(/ᵒ/g, "o")
	str = str.replace(/ʷ/g, "w")
	str = str.replace(/ᵉ/g, "ē")
	str = str.replace(/e/g, "ē")
	str = str.replace(/j/g, "y")
	str = str.replace(/\u202F/g, "-")
	str = str.replace(/\u00A0/g, "-")

	return str.trim().toLowerCase()
	}



function reverseX (str) { 
    
str += '  '

str = str.replace(/kpe/g, "ꔉ")
str = str.replace(/mgbe/g, "ꔊ")
str = str.replace(/gbe/g, "ꔋ")
str = str.replace(/mɓe/g, "ꔈ")
str = str.replace(/nɗe/g, "ꔕ")
str = str.replace(/nʤe/g, "ꔜ")
str = str.replace(/ŋge/g, "ꔟ")
str = str.replace(/ẹ̃/g, "ꔁ")
str = str.replace(/ẹ/g, "ꔀ")
str = str.replace(/he/g, "ꔂ")
str = str.replace(/wẽ/g, "ꔄ")
str = str.replace(/we/g, "ꔃ")
str = str.replace(/pe/g, "ꔅ")
str = str.replace(/be/g, "ꔆ")
str = str.replace(/ɓe/g, "ꔇ")
str = str.replace(/fe/g, "ꔌ")
str = str.replace(/ve/g, "ꔍ")
str = str.replace(/te/g, "ꔎ")
str = str.replace(/θe/g, "ꔏ")
str = str.replace(/de/g, "ꔐ")
str = str.replace(/ðe/g, "ꔑ")
str = str.replace(/le/g, "ꔒ")
str = str.replace(/re/g, "ꔓ")
str = str.replace(/ɗe/g, "ꔔ")
str = str.replace(/se/g, "ꔖ")
str = str.replace(/ʃe/g, "ꔗ")
str = str.replace(/ze/g, "ꔘ")
str = str.replace(/ʒe/g, "ꔙ")
str = str.replace(/ʧe/g, "ꔚ")
str = str.replace(/ʤe/g, "ꔛ")
str = str.replace(/je/g, "ꔝ")
str = str.replace(/ke/g, "ꔞ")
str = str.replace(/ge/g, "ꔠ")
str = str.replace(/mẽ/g, "ꔡ")
str = str.replace(/nẽ/g, "ꔢ")
str = str.replace(/ɲẽ/g, "ꔣ")

str = str.replace(/mɓi/g, "ꔭ")
str = str.replace(/kpi/g, "ꔮ")
str = str.replace(/mgbi/g, "ꔯ")
str = str.replace(/gbi/g, "ꔰ")
str = str.replace(/nɗi/g, "ꔺ")
str = str.replace(/nʤi/g, "ꕁ")
str = str.replace(/ŋgi/g, "ꕄ")
str = str.replace(/ị̃/g, "ꔥ")
str = str.replace(/ị/g, "ꔤ")
str = str.replace(/hĩ/g, "ꔧ")
str = str.replace(/hi/g, "ꔦ")
str = str.replace(/wĩ/g, "ꔩ")
str = str.replace(/wi/g, "ꔨ")
str = str.replace(/pi/g, "ꔪ")
str = str.replace(/bi/g, "ꔫ")
str = str.replace(/ɓi/g, "ꔬ")
str = str.replace(/fi/g, "ꔱ")
str = str.replace(/vi/g, "ꔲ")
str = str.replace(/ti/g, "ꔳ")
str = str.replace(/θi/g, "ꔴ")
str = str.replace(/di/g, "ꔵ")
str = str.replace(/ði/g, "ꔶ")
str = str.replace(/li/g, "ꔷ")
str = str.replace(/ri/g, "ꔸ")
str = str.replace(/ɗi/g, "ꔹ")
str = str.replace(/si/g, "ꔻ")
str = str.replace(/ʃi/g, "ꔼ")
str = str.replace(/zi/g, "ꔽ")
str = str.replace(/ʒi/g, "ꔾ")
str = str.replace(/ʧi/g, "ꔿ")
str = str.replace(/ʤi/g, "ꕀ")
str = str.replace(/ji/g, "ꕂ")
str = str.replace(/ki/g, "ꕃ")
str = str.replace(/gi/g, "ꕅ")
str = str.replace(/mĩ/g, "ꕆ")
str = str.replace(/nĩ/g, "ꕇ")
str = str.replace(/ɲĩ/g, "ꕈ")

str = str.replace(/mɓa/g, "ꕓ")
str = str.replace(/kpã/g, "ꕕ")
str = str.replace(/kpa/g, "ꕔ")
str = str.replace(/mgba/g, "ꕖ")
str = str.replace(/gba/g, "ꕗ")
str = str.replace(/nɗa/g, "ꕡ")
str = str.replace(/nʤa/g, "ꕨ")
str = str.replace(/ŋga/g, "ꕬ")
str = str.replace(/ạ̃/g, "ꕊ")
str = str.replace(/ạ/g, "ꕉ")
str = str.replace(/ŋã/g, "ꕋ")
str = str.replace(/hã/g, "ꕍ")
str = str.replace(/ha/g, "ꕌ")
str = str.replace(/wã/g, "ꕏ")
str = str.replace(/wa/g, "ꕎ")
str = str.replace(/pa/g, "ꕐ")
str = str.replace(/ba/g, "ꕑ")
str = str.replace(/ɓa/g, "ꕒ")
str = str.replace(/fa/g, "ꕘ")
str = str.replace(/va/g, "ꕙ")
str = str.replace(/ta/g, "ꕚ")
str = str.replace(/θa/g, "ꕛ")
str = str.replace(/da/g, "ꕜ")
str = str.replace(/ða/g, "ꕝ")
str = str.replace(/la/g, "ꕞ")
str = str.replace(/ra/g, "ꕟ")
str = str.replace(/ɗa/g, "ꕠ")
str = str.replace(/sa/g, "ꕢ")
str = str.replace(/ʃa/g, "ꕣ")
str = str.replace(/za/g, "ꕤ")
str = str.replace(/ʒa/g, "ꕥ")
str = str.replace(/ʧa/g, "ꕦ")
str = str.replace(/ʤa/g, "ꕧ")
str = str.replace(/ja/g, "ꕩ")
str = str.replace(/kã/g, "ꕫ")
str = str.replace(/ka/g, "ꕪ")
str = str.replace(/ga/g, "ꕭ")
str = str.replace(/mã/g, "ꕮ")
str = str.replace(/nã/g, "ꕯ")
str = str.replace(/ɲã/g, "ꕰ")

str = str.replace(/mɓo/g, "ꕹ")
str = str.replace(/kpo/g, "ꕺ")
str = str.replace(/mgbo/g, "ꕻ")
str = str.replace(/gbo/g, "ꕼ")
str = str.replace(/nɗo/g, "ꖆ")
str = str.replace(/nʤo/g, "ꖍ")
str = str.replace(/ŋgo/g, "ꖐ")
str = str.replace(/ọ̃/g, "ꕲ")
str = str.replace(/ọ/g, "ꕱ")
str = str.replace(/ho/g, "ꕳ")
str = str.replace(/wõ/g, "ꕵ")
str = str.replace(/wo/g, "ꕴ")
str = str.replace(/po/g, "ꕶ")
str = str.replace(/bo/g, "ꕷ")
str = str.replace(/ɓo/g, "ꕸ")
str = str.replace(/fo/g, "ꕽ")
str = str.replace(/vo/g, "ꕾ")
str = str.replace(/to/g, "ꕿ")
str = str.replace(/θo/g, "ꖀ")
str = str.replace(/do/g, "ꖁ")
str = str.replace(/ðo/g, "ꖂ")
str = str.replace(/lo/g, "ꖃ")
str = str.replace(/ro/g, "ꖄ")
str = str.replace(/ɗo/g, "ꖅ")
str = str.replace(/so/g, "ꖇ")
str = str.replace(/ʃo/g, "ꖈ")
str = str.replace(/zo/g, "ꖉ")
str = str.replace(/ʒo/g, "ꖊ")
str = str.replace(/ʧo/g, "ꖋ")
str = str.replace(/ʤo/g, "ꖌ")
str = str.replace(/jo/g, "ꖎ")
str = str.replace(/ko/g, "ꖏ")
str = str.replace(/go/g, "ꖑ")
str = str.replace(/mõ/g, "ꖒ")
str = str.replace(/nõ/g, "ꖓ")
str = str.replace(/ɲõ/g, "ꖔ")

str = str.replace(/mɓu/g, "ꖞ")
str = str.replace(/kpu/g, "ꖟ")
str = str.replace(/mgbu/g, "ꖠ")
str = str.replace(/gbu/g, "ꖡ")
str = str.replace(/nɗu/g, "ꖫ")
str = str.replace(/nʤu/g, "ꖲ")
str = str.replace(/ŋgu/g, "ꖵ")
str = str.replace(/ụ̃/g, "ꖖ")
str = str.replace(/ụ/g, "ꖕ")
str = str.replace(/hũ/g, "ꖘ")
str = str.replace(/hu/g, "ꖗ")
str = str.replace(/wũ/g, "ꖚ")
str = str.replace(/wu/g, "ꖙ")
str = str.replace(/pu/g, "ꖛ")
str = str.replace(/bu/g, "ꖜ")
str = str.replace(/ɓu/g, "ꖝ")
str = str.replace(/fu/g, "ꖢ")
str = str.replace(/vu/g, "ꖣ")
str = str.replace(/tu/g, "ꖤ")
str = str.replace(/θu/g, "ꖥ")
str = str.replace(/du/g, "ꖦ")
str = str.replace(/ðu/g, "ꖧ")
str = str.replace(/lu/g, "ꖨ")
str = str.replace(/ru/g, "ꖩ")
str = str.replace(/ɗu/g, "ꖪ")
str = str.replace(/su/g, "ꖬ")
str = str.replace(/ʃu/g, "ꖭ")
str = str.replace(/zu/g, "ꖮ")
str = str.replace(/ʒu/g, "ꖯ")
str = str.replace(/ʧu/g, "ꖰ")
str = str.replace(/ʤu/g, "ꖱ")
str = str.replace(/ju/g, "ꖳ")
str = str.replace(/ku/g, "ꖴ")
str = str.replace(/gu/g, "ꖶ")
str = str.replace(/mũ/g, "ꖷ")
str = str.replace(/nũ/g, "ꖸ")
str = str.replace(/ɲũ/g, "ꖹ")

str = str.replace(/mɓɔ/g, "ꗄ")
str = str.replace(/kpɔ/g, "ꗅ")
str = str.replace(/mgbɔ/g, "ꗆ")
str = str.replace(/gbɔ̃/g, "ꗈ")
str = str.replace(/gbɔ/g, "ꗇ")
str = str.replace(/nɗɔ/g, "ꗒ")
str = str.replace(/nʤɔ/g, "ꗙ")
str = str.replace(/ŋgɔ/g, "ꗜ")
str = str.replace(/ɔ̣̃/g, "ꖻ")
str = str.replace(/ɔ̣/g, "ꖺ")
str = str.replace(/ŋɔ/g, "ꖼ")
str = str.replace(/hɔ̃/g, "ꖾ")
str = str.replace(/hɔ/g, "ꖽ")
str = str.replace(/wɔ̃/g, "ꗀ")
str = str.replace(/wɔ/g, "ꖿ")
str = str.replace(/pɔ/g, "ꗁ")
str = str.replace(/bɔ/g, "ꗂ")
str = str.replace(/ɓɔ/g, "ꗃ")
str = str.replace(/fɔ/g, "ꗉ")
str = str.replace(/vɔ/g, "ꗊ")
str = str.replace(/tɔ/g, "ꗋ")
str = str.replace(/θɔ/g, "ꗌ")
str = str.replace(/dɔ/g, "ꗍ")
str = str.replace(/ðɔ/g, "ꗎ")
str = str.replace(/lɔ/g, "ꗏ")
str = str.replace(/rɔ/g, "ꗐ")
str = str.replace(/ɗɔ/g, "ꗑ")
str = str.replace(/sɔ/g, "ꗓ")
str = str.replace(/ʃɔ/g, "ꗔ")
str = str.replace(/zɔ/g, "ꗕ")
str = str.replace(/ʒɔ/g, "ꗖ")
str = str.replace(/ʧɔ/g, "ꗗ")
str = str.replace(/ʤɔ/g, "ꗘ")
str = str.replace(/jɔ/g, "ꗚ")
str = str.replace(/kɔ/g, "ꗛ")
str = str.replace(/gɔ/g, "ꗝ")
str = str.replace(/mɔ̃/g, "ꗞ")
str = str.replace(/nɔ̃/g, "ꗟ")
str = str.replace(/ɲɔ̃/g, "ꗠ")

str = str.replace(/mɓɛ/g, "ꗫ")
str = str.replace(/kpɛ̃/g, "ꗭ")
str = str.replace(/kpɛ/g, "ꗬ")
str = str.replace(/mgbɛ/g, "ꗮ")
str = str.replace(/gbɛ̃/g, "ꗰ")
str = str.replace(/gbɛ/g, "ꗯ")
str = str.replace(/nɗɛ/g, "ꗺ")
str = str.replace(/nʤɛ/g, "ꘁ")
str = str.replace(/ŋgɛ̃/g, "ꘅ")
str = str.replace(/ŋgɛ/g, "ꘄ")
str = str.replace(/ɛ̣̃/g, "ꗢ")
str = str.replace(/ɛ̣/g, "ꗡ")
str = str.replace(/ŋɛ̃/g, "ꗣ")
str = str.replace(/hɛ̃/g, "ꗥ")
str = str.replace(/hɛ/g, "ꗤ")
str = str.replace(/wɛ̃/g, "ꗧ")
str = str.replace(/wɛ/g, "ꗦ")
str = str.replace(/pɛ/g, "ꗨ")
str = str.replace(/bɛ/g, "ꗩ")
str = str.replace(/ɓɛ/g, "ꗪ")
str = str.replace(/fɛ/g, "ꗱ")
str = str.replace(/vɛ/g, "ꗲ")
str = str.replace(/tɛ/g, "ꗳ")
str = str.replace(/θɛ/g, "ꗴ")
str = str.replace(/dɛ/g, "ꗵ")
str = str.replace(/ðɛ/g, "ꗶ")
str = str.replace(/lɛ/g, "ꗷ")
str = str.replace(/rɛ/g, "ꗸ")
str = str.replace(/ɗɛ/g, "ꗹ")
str = str.replace(/sɛ/g, "ꗻ")
str = str.replace(/ʃɛ/g, "ꗼ")
str = str.replace(/zɛ/g, "ꗽ")
str = str.replace(/ʒɛ/g, "ꗾ")
str = str.replace(/ʧɛ/g, "ꗿ")
str = str.replace(/ʤɛ/g, "ꘀ")
str = str.replace(/jɛ/g, "ꘂ")
str = str.replace(/kɛ/g, "ꘃ")
str = str.replace(/gɛ̃/g, "ꘇ")
str = str.replace(/gɛ/g, "ꘆ")
str = str.replace(/mɛ̃/g, "ꘈ")
str = str.replace(/nɛ̃/g, "ꘉ")
str = str.replace(/ɲɛ̃/g, "ꘊ")

// syllable finals
str = str.replace(/ŋ̽/g, "ꘋ")
str = str.replace(/–/g, "ꘌ")

// logograms
str = str.replace(/FAA/g, "ꘘ")
str = str.replace(/FENG/g, "ꘓ")

str = str.replace(/FEŊ/g, "ꘓ")
str = str.replace(/KEŊ/g, "ꘔ")
str = str.replace(/TIŊ/g, "ꘕ")
str = str.replace(/NII/g, "ꘖ")
str = str.replace(/BAŊ/g, "ꘗ")
str = str.replace(/TAA/g, "ꘙ")
str = str.replace(/DAŊ/g, "ꘚ")
str = str.replace(/DOŊ/g, "ꘛ")
str = str.replace(/KUŊ/g, "ꘜ")
str = str.replace(/TƆŊ/g, "ꘝ")
str = str.replace(/DƆƆ̣/g, "ꘞ")
str = str.replace(/JƆŊ/g, "ꘟ")


// punctuation
str = str.replace(/,/g, "꘍")
str = str.replace(/!/g, "꘎꘎")
str = str.replace(/\./g, "꘎")
str = str.replace(/\?/g, "꘏")

// numbers
str = str.replace(/0/g, "꘠")
str = str.replace(/1/g, "꘡")
str = str.replace(/2/g, "꘢")
str = str.replace(/3/g, "꘣")
str = str.replace(/4/g, "꘤")
str = str.replace(/5/g, "꘥")
str = str.replace(/6/g, "꘦")
str = str.replace(/7/g, "꘧")
str = str.replace(/8/g, "꘨")
str = str.replace(/9/g, "꘩")



return str.trim()
}



