charData["\u0E2F\u0E25\u0E2F"]="THAI CHARACTER PAIYANNOI, CHARACTER LO LING, CHARACTER PAIYANNOI"
charData["\u0E24\u0E45"]="THAI CHARACTER RU, CHARACTER LAKKHANGYAO"
charData["\u0E26\u0E45"]="THAI CHARACTER LU, CHARACTER LAKKHANGYAO"
