charData["\u0EC6\u0EA5\u0EC6"]="LAO KO LA, LAO LETTER LO LOOT, LAO KO LA"
charData["\u0EAB\u0EBC"]="LAO LETTER HO SUNG, SEMIVOWEL SIGN LO"
charData["\u0EC0\u0EB0"]="LAO LETTER VOWEL SIGN E, VOWEL SIGN A"
